### ISSUE TITLE
Update to support VirtualBox 5.2

### ISSUE THREAD

**Issue by Artistan** [chef/bento#944] opened 2017-11-28 20:51 UTC
vboxsf: Unknown symbol VBoxGuestIDC (err 0)

https://github.com/hashicorp/vagrant/issues/8303#issuecomment-283164346

> Proper installation of guest additions within the box will resolve the synced folder issue.

https://www.virtualbox.org/ticket/17189?cversion=0&cnum_hist=5

> ... the message about "modprobe vboxsf failed" may still appear, as it is caused by the old Guest Additions which are being removed, not the new ones being installed.

Error examples....
Linux homestead 4.4.0-92-generic #115-Ubuntu SMP Thu Aug 10 09:04:33 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

https://gist.github.com/Artistan/199c8b6c988ad9c20fbeda5dc8218b24

Using Laravel/Homestead, which uses 
https://app.vagrantup.com/bento/boxes/ubuntu-16.04-i386/versions/201710.25.0

**Comment by Artistan** [comment] 2017-11-28 21:14
testing a new build on my box using bento configs.

**Comment by Artistan** [comment] 2017-11-29 02:38
Yep, simply rebuilding the box with updated Guest Additions worked.

https://gist.github.com/Artistan/523b7274ae89cb77b5bd66d8bf0bb8f4

**Comment by Artistan** [comment] 2017-11-29 06:32
Took it a step further, for those who want to stay bleeding edge. https://github.com/Artistan/homestead-builder

**Comment by cheeseplus** [comment] 2017-11-29 18:57
A big part of the problem is that we're chose not to build against VirtualBox 5.2 at the time because the current release of Vagrant didn't support it. There were also other issues with the most recent two Vagrant releases that essentially broke an entire platform so it didn't seem worth cutting releases that nobody could use. We'll be building new images against 5.2 once I can validate that some of the other dependent tools are in good working order at latest versions as well.

I'm not sure this is really a bug, at least the real issues here would be 'Support VirtualBox 5.2'

**Comment by Artistan** [comment] 2017-11-29 19:23
fair enough. it is not a bug in bento, but there is not a current bento release that works with the updated virtual box and additions, hence the report.  So far it is working fine for me with hte setup I posted above.

**Comment by cheeseplus** [comment] 2017-11-30 15:17
Cool, just wanted to make sure I understood the report - we're definitely aware that we need to build against 5.2 but the timing of the last build just happened to be right before Vagrant supported it. They definitely build with 5.2, at least last I ran it through so shipping new ones shouldn't be much extra work if any.

**Comment by cheeseplus** [comment] 2018-01-05 17:03
Fixed by #971

**Closed by cheeseplus** 2018-01-05 17:03 UTC
