### ISSUE TITLE
RHEL build script fails due to yum install

### ISSUE THREAD

**Issue by howardjones** [chef/bento#1176] opened 2019-02-15 14:29 UTC
If you use the RHEL 7 (at least, I haven't checked 6 yet) packer template, it shares all its provisioning scripts with CentOS. This is all fine until the very end of `cleanup.sh` where the `yum install` will fail because the system isn't registered with RedHat/RHUI. Moving the required package `yum-utils` into the kickstart file instead resolves the issue without any other impact (that I can think of, at least).

Sorry, I can't submit a PR for this.

**Comment by cheeseplus** [comment] 2019-02-15 20:01
This is known and it's a dupe of https://github.com/chef/bento/issues/1093

**Closed by cheeseplus** 2019-02-15 20:01 UTC
