### ISSUE TITLE
Vagrant init has a problem with ssh-key connection

### ISSUE THREAD

**Issue by andkirby** [chef/bento#655] opened 2016-09-06 13:33 UTC
I've faced an issue by subject.
http://stackoverflow.com/questions/39350227/cannot-make-vagrant-ssh-key-using-connection-in-base-initializing-authorized-ke
Can it be your issue?
Maybe .ssh directory must have 600 (I don't know it's created by default or not)

Or may [this](https://github.com/mitchellh/vagrant/issues/7610) is related.

**Comment by cheeseplus** [comment] 2016-09-06 13:50
Are you using Vagrant 1.8.5? If so, it's Vagrant.

**Comment by cheeseplus** [comment] 2016-09-06 13:55
Closing this as answered on SO - please avoid cross posting.

**Comment by legal90** [comment] 2016-09-06 13:55
Yep, it is caused  by https://github.com/mitchellh/vagrant/issues/7610 and was already fixed in Vagrant's master branch (https://github.com/mitchellh/vagrant/pull/7611). 

The problem is not in the `.ssh` directory, but in  the `.ssh/authorized_keys` file, which Vagrant replaces during the new SSH key pair insertion. So, it's not an issue of Bento and could not be fixed on our side.

There are two suggestions at the moment to work it around:
1) Downgrade to Vagrant 1.8.4
2) Disable the insertion of the new ssh key pair:
```ruby
# In your Vagrantfile
config.ssh.insert_key = false
```

P.s. And yes, waiting for Vagrant 1.8.6 release is also an option ;)

**Closed by cheeseplus** 2016-09-06 13:55 UTC

**Comment by andkirby** [comment] 2016-09-06 14:00
Thank you, guys, for confirming and explanation.
