### ISSUE TITLE
Please update the CentOS 7 box

### ISSUE THREAD

**Issue by hwoarang** [chef/bento#1040] opened 2018-05-14 11:53 UTC
Hello,

Would it be possible to update the CentOS 7 boxes? The current one comes with a very old dbus compared to the ``1.10`` which is available and this results to a bug similar to this

``https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=793519``

As such, the box needs to be updated and then rebooted in order to become fully functional. This causes troubles in automated testing.

Thank you

**Comment by fletchowns** [comment] 2018-05-14 16:31
Looks like CentOS 7.5 was just released last week: https://lists.centos.org/pipermail/centos-announce/2018-May/022829.html

**Comment by cheeseplus** [comment] 2018-05-14 16:49
We've got 3 "please update" issues at present - I am aware but am currently tasked on high priority work so the best I can offer is "I'll get these when I have a moment"

**Comment by cheeseplus** [comment] 2018-05-14 16:57
Closing as dupe of #1039 (because we don't need multiple issues tracking the same release)

**Comment by bertvv** [comment] 2018-06-04 14:41
Er, @cheeseplus, this issue doesn't seem to be closed?

There seems to be a version for Centos 7.5 at https://app.vagrantup.com/bento/boxes/centos-7.5
However, it doesn't seem to be released officially.

**Comment by cheeseplus** [comment] 2018-06-04 16:20
I know it isn't closed but having multiple open issues asking me to "update" the images doesn't do us much good. I've been busy with ChefConf and PTO, images will be forthcoming once I've ensured that all testing has passed as there were some last minute issues that have come up.

I'm targeting this week for a release but might let the last round of builds out in the interim. Sorry for the wait!

**Comment by cheeseplus** [comment] 2018-06-04 21:12
Closing - https://app.vagrantup.com/bento/boxes/centos-7.5/versions/201805.15.0

Changelog will be updated as soon as possible but this resolves this specific issue.

**Closed by cheeseplus** 2018-06-04 21:12 UTC

**Comment by bertvv** [comment] 2018-06-05 19:09
Awesome, thank you so much!
