### ISSUE TITLE
Windows Boot Manger on Waiting for WinRM to become available

### ISSUE THREAD

**Issue by bcorner13** [chef/bento#979] opened 2018-01-23 17:34 UTC
Getting the Windows Boot Manager with a message of A recent hardware or software change might have installed a file that is signed incorrectly or damaged.....  
File: \windows\system32\boot\winload.exe
Status: 0xc0000605
Info:  Component of the operating system has expired.

![screen shot 2018-01-23 at 12 34 25 pm](https://user-images.githubusercontent.com/3322432/35290955-d071f892-0039-11e8-8d9f-3cfcbd9188bf.png)

**Comment by cheeseplus** [comment] 2018-01-23 20:02
Dupe of https://github.com/chef/bento/issues/938 - we aren't supporting this image any longer (we didn't really support it much to begin with) as Nano itself has also changed directions from this release. The template will be removed shortly as it's entirely broken and non-functional.

**Closed by cheeseplus** 2018-01-23 20:02 UTC
