### ISSUE TITLE
Unknown repo: 'C*-base' when using bento/centos-8.2

### ISSUE THREAD

**Issue by JingMa87** [chef/bento#1307] opened 2020-09-21 00:00 UTC
# Describe the problem
When using the bento/centos-8.2 box, the `vagrant up` step fails with the error `Unknown repo: 'C*-base'`. I'm getting the same error when repeating the steps with a bento/centos-8.1 box. The cause is upgrading to VirtualBox 6.1.14 from 6.1.12.

## Software Version
Vagrant 2.2.10
bento/centos-8.2 (v202008.16.0)
VirtualBox 6.1.14
MacOS Catalina 10.15.6

## Replication Case
- vagrant box add bento/centos-8.2
- vagrant init bento/centos-8.2
- vagrant up

## Stacktrace
```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

yum install -y kernel-devel-`uname -r` --enablerepo=C*-base --enablerepo=C*-updates

Stdout from the command:
Stderr from the command:

Error: Unknown repo: 'C*-base'
```

## Possible Solution
No idea

![image](https://user-images.githubusercontent.com/16444164/93725133-ec8f9180-fbac-11ea-9d46-78b7e104e219.png)

**Comment by tas50** [comment] 2020-10-24 19:30
```
❰tsmith❙~❱✔≻ vagrant init bento/centos-8.2
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
❰tsmith❙~❱✔≻ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'bento/centos-8.2'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'bento/centos-8.2' version '202010.22.0' is up to date...
==> default: Setting the name of the VM: tsmith_default_1603567791659_98154
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => /Users/tsmith
```

I'm unable to reproduce this with the new boxes I built so I'm going to close this out.

**Closed by tas50** 2020-10-24 19:30 UTC
