### ISSUE TITLE
Ubuntu 14.04 VMware HGFS modules not loaded

### ISSUE THREAD

**Issue by mitchellh** [chef/bento#283] opened 2014-10-19 18:34 UTC
Hi! It looks like the HGFS modules aren't properly installed (or they break at some point) for the Ubuntu 14.04 box. Let me know if I can help in any way. Thanks!

**Comment by thasmo** [comment] 2015-01-18 15:15
@juliandunn, any progress on the VMWare upgrade?

**Comment by juliandunn** [comment] 2015-01-24 00:09
Yes, I procured a VMWare Fusion 7 license. Those of you who are having problems, can you check out this scratch build:

https://jdunn-getchef-scratch.s3.amazonaws.com/opscode_ubuntu-14.04_chef-provisionerless.box

and let me know if that fixes the issue? It has been built with Fusion 7.0.3.

**Comment by thasmo** [comment] 2015-01-24 01:35
@juliandunn, thanks a lot - works for me using Workstation 11 on Windows 8.1. Are you going to update the Ubuntu 14.10 boxes on Atlas also?

**Comment by juliandunn** [comment] 2015-01-24 03:50
@thasmo Yes, I will have to rebuild everything for Fusion 7.

**Comment by juliandunn** [comment] 2015-01-31 21:38
I have rebuilt at least the 14.04 boxes for VMWare Fusion 7 and put them on Atlas.

**Comment by thasmo** [comment] 2015-01-31 22:14
@juliandunn, nice! What about the other boxes including Ubuntu 14.10?

**Comment by juliandunn** [comment] 2015-02-01 16:34
@thasmo Haven't finished building those yet.

**Comment by packetcollision** [comment] 2015-02-02 23:50
I still only see version 1.0.0 on the atlas site. Was this a silent update? Removing the box from my machine and re-downloading it seems to have fixed things, so I assume so. Can we get a revision bump so people can just run `vagrant box update` to get the fix?

**Comment by beddari** [comment] 2015-02-04 08:11
As far as I know versioning boxes on Atlas is outside the scope of the project ...

**Comment by juliandunn** [comment] 2015-02-04 15:13
That's correct, we currently do not version boxes in this project. Some day we might, but there are no resources presently to do that level of integration with Atlas.

**Comment by packetcollision** [comment] 2015-02-04 17:23
OK, thanks for providing the boxes!

**Comment by thasmo** [comment] 2015-02-25 23:27
@juliandunn, did you already have time to build new 14.10 boxes? The ones on Atlas currently don't work with VMware Workstation 11.

**Comment by juliandunn** [comment] 2015-02-26 01:22
@thasmo I just uploaded them. Sorry about that - thought I'd done so already.

**Comment by thasmo** [comment] 2015-02-26 08:22
@juliandunn, np - thanks for providing them! :)

**Comment by yourabi** [comment] 2015-02-26 19:19
So is the takeaway that we need Atlas accounts to continue using these images?

**Comment by josegonzalez** [comment] 2015-03-12 20:43
Seems the current images don't work with Vmware Fusion 7.1.1 Pro, can anyone else confirm?

**Comment by jvanbaarsen** [comment] 2015-04-13 10:03
I can confirm that the current image does not work with VmWare Fusion 7.1.1 Pro.

**Comment by bklang** [comment] 2015-06-21 21:33
I'm seeing the same issue with VMware Fusion 7.1.1.  The advice given above to log into the guest and run `sudo-vmware-config-tools.pl` seems to be the best workaround. Note that in my case I needed to first install the `gcc` and `linux-headers-$(uname -r)` packages.  My guess is that this will be a bit of a cat-and-mouse game, with the VMware Tools getting updated, and the guest box being out of date.

**Comment by fnichol** [comment] 2015-06-22 22:48
I will try a run against VMware Fusion 7.1.2 which came out only a day or 2 ago. It was a major blocker for any newer kernel version working with HGFS. Sad pandas all around.

**Comment by geerlingguy** [comment] 2015-06-23 19:05
Seeing similar issues with my (non-bento) boxes for CentOS 6 and 7, Ubuntu 12.04 and 14.04: https://github.com/geerlingguy/ansible-role-packer-debian/issues/3 and https://github.com/geerlingguy/ansible-role-packer-rhel/issues/4 — I have CentOS 6 fixed now (using Ansible to do the installation steps), but I'm still working on the other 3 OSes. Just wanted to link these issues as the work/solutions in the tickets can build off each other.

**Comment by jtimberman** [comment] 2015-07-16 05:51
Also seeing HGFS module hang. I downloaded the current box to my system:

```
% kitchen converge
-----> Starting Kitchen (v1.4.1)
-----> Creating <default-ubuntu-1404>...
       Bringing machine 'default' up with 'vmware_fusion' provider...
       ==> default: Box 'opscode-ubuntu-14.04' could not be found. Attempting to find and install...
           default: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
           default: Box Version: >= 0
       ==> default: Adding box 'opscode-ubuntu-14.04' (v0) for provider: vmware_desktop, vmware_fusion, vmware_workstation
           default: Downloading: https://opscode-vm-bento.s3.amazonaws.com/vagrant/vmware/opscode_ubuntu-14.04_chef-provisionerless.box
==> default: Successfully added box 'opscode-ubuntu-14.04' (v0) for 'vmware_desktop'!
       ==> default: Cloning VMware VM: 'opscode-ubuntu-14.04'. This can take some time...
       ==> SNIP SNIP
       ==> default: Waiting for HGFS kernel module to load...
```

I let it go until it ultimately timed out.

**Comment by tisba** [comment] 2015-09-03 21:39
I'm running into the same issue using VMware Fusion Version 8.0.0 (2985594) on OS X 10.10.5 (with Ubuntu 14.04).

**Comment by cheeseplus** [comment] 2015-09-03 21:50
Pretty sure this is the same issue as #377 or at the very least related.

**Comment by tisba** [comment] 2015-09-06 12:35
@mathiasson @bklang Do you still have success with installing the VMware Tools again with VMware Fusion Version 8.0.0 (2985594)? I just cannot get it to work at all currently :-/

**Comment by bklang** [comment] 2015-09-09 15:17
@tisba Sorry, I no longer use Vagrant with Fusion so I can't say.

**Comment by tiwilliam** [comment] 2015-09-18 15:37
Got same error when building my own box and this doesn't look alright:
```
==> vmware-iso: Provisioning with shell script: scripts/common/vmtools.sh
    vmware-iso: + HOME_DIR=/home/vagrant
    vmware-iso: + mkdir -p /tmp/vmfusion
    vmware-iso: + mkdir -p /tmp/vmfusion-archive
    vmware-iso: + mount -o loop /home/vagrant/linux.iso /tmp/vmfusion
    vmware-iso: mount: block device /home/vagrant/linux.iso is write-protected, mounting read-only
    vmware-iso: + tar xzf /tmp/vmfusion/VMwareTools-10.0.0-2977863.tar.gz -C /tmp/vmfusion-archive
    vmware-iso: + /tmp/vmfusion-archive/vmware-tools-distrib/vmware-install.pl --default
    vmware-iso: open-vm-tools are available from the OS vendor and VMware recommends using
    vmware-iso: open-vm-tools. See http://kb.vmware.com/kb/2073803 for more information.
    vmware-iso: Do you still want to proceed with this legacy installer? [no]
    vmware-iso:
    vmware-iso: + umount /tmp/vmfusion
    vmware-iso: + rm -rf /tmp/vmfusion
    vmware-iso: + rm -rf /tmp/vmfusion-archive
    vmware-iso: + rm -f /home/vagrant/linux.iso
```

**Comment by tiwilliam** [comment] 2015-09-18 16:08
Confirmed working when switching from `default` to `force-install`, not sure if this have any other side effects:
```diff
-    /tmp/vmfusion-archive/vmware-tools-distrib/vmware-install.pl --default;
+    /tmp/vmfusion-archive/vmware-tools-distrib/vmware-install.pl --force-install;
```

**Comment by tisba** [comment] 2015-09-20 12:35
There is a lot of output[0], pointing to using "open-vm-tools" (http://kb.vmware.com/kb/2073803). I'm not very experienced when it comes to this stuff, but I wasn't able to get shared folders to work using just "open-vm-tools".

Anyhow, when I patch vmtools.sh as described by @tiwilliam it seems to work fine.

[0]: https://gist.github.com/tisba/2c5a9627e9cef2da786a

**Comment by phinze** [comment] 2015-09-21 14:37
Hey folks, I'm also unable to get `open-vm-tools` to load the hgfs kernel moadule.

Relevant reading:

 * https://communities.vmware.com/thread/474260
 * https://github.com/rasa/vmware-tools-patches/issues/29

Seems like the `--force-install` workaround is worth adding for now, yeah?

**Closed** 2015-09-22 08:32 UTC
Labels: Developing
