### ISSUE TITLE
'bento/ubuntu-*' v2.3.0 boxes hang on ssh

### ISSUE THREAD

**Issue by lhagemann** [chef/bento#694] opened 2016-10-12 21:15 UTC
Trying to init a fresh vagrant environment using the latest bento boxes and observe failure to ssh into the box. (output below includes a `^C` but if left to run, would eventually timeout.

I observe the latest bento releases change the UID of the vagrant user. 

my environment:
OSX 10.10.5 
```
$ vagrant --version
Vagrant 1.8.6
$ brew cask info virtualbox
virtualbox: 5.1.4-110228
```

```
$ vagrant init bento/ubuntu-14.04; vagrant up --provider virtualbox
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'bento/ubuntu-14.04' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'bento/ubuntu-14.04'
    default: URL: https://atlas.hashicorp.com/bento/ubuntu-14.04
==> default: Adding box 'bento/ubuntu-14.04' (v2.3.0) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/bento/boxes/ubuntu-14.04/versions/2.3.0/providers/virtualbox.box
==> default: Successfully added box 'bento/ubuntu-14.04' (v2.3.0) for 'virtualbox'!
==> default: Importing base box 'bento/ubuntu-14.04'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'bento/ubuntu-14.04' is up to date...
==> default: Setting the name of the VM: tmp_default_1476305704427_90059
==> default: Fixed port collision for 22 => 2222. Now on port 2202.
==> default: Clearing any previously set network interfaces...
==> default: translation missing: en.servicemanager.action.private_network
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2202 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2202
    default: SSH username: vagrant
    default: SSH auth method: private key
^C==> default: Waiting for cleanup before exiting...


$ vagrant init bento/ubuntu-12.04; vagrant up --provider virtualbox
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'bento/ubuntu-12.04' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'bento/ubuntu-12.04'
    default: URL: https://atlas.hashicorp.com/bento/ubuntu-12.04
==> default: Adding box 'bento/ubuntu-12.04' (v2.3.0) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/bento/boxes/ubuntu-12.04/versions/2.3.0/providers/virtualbox.box
==> default: Successfully added box 'bento/ubuntu-12.04' (v2.3.0) for 'virtualbox'!
==> default: Importing base box 'bento/ubuntu-12.04'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'bento/ubuntu-12.04' is up to date...
==> default: Setting the name of the VM: tmp_default_1476306666523_91243
==> default: Fixed port collision for 22 => 2222. Now on port 2203.
==> default: Clearing any previously set network interfaces...
==> default: translation missing: en.servicemanager.action.private_network
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 (guest) => 2203 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2203
    default: SSH username: vagrant
    default: SSH auth method: private key
^C==> default: Waiting for cleanup before exiting...

```

**Comment by neilschelly** [comment] 2016-10-12 21:33
I can confirm this is an issue only with the latest build. I had this problem with 16.04, 14.04, and didn't try 12.04.

```
17:24 nschelly@serenity: ~/work/tmp$ vagrant init --box-version 2.2.9 bento/ubuntu-14.04
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
17:25 nschelly@serenity: ~/work/tmp$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'bento/ubuntu-14.04' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: 2.2.9
==> default: Loading metadata for box 'bento/ubuntu-14.04'
    default: URL: https://atlas.hashicorp.com/bento/ubuntu-14.04
==> default: Adding box 'bento/ubuntu-14.04' (v2.2.9) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/bento/boxes/ubuntu-14.04/versions/2.2.9/providers/virtualbox.box
==> default: Successfully added box 'bento/ubuntu-14.04' (v2.2.9) for 'virtualbox'!
==> default: Importing base box 'bento/ubuntu-14.04'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'bento/ubuntu-14.04' is up to date...
==> default: Setting the name of the VM: tmp_default_1476307541436_67697
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
    default:
    default: Vagrant insecure key detected. Vagrant will automatically replace
    default: this with a newly generated keypair for better security.
    default:
    default: Inserting generated public key within guest...
    default: Removing insecure key from the guest if it's present...
    default: Key inserted! Disconnecting and reconnecting using new SSH key...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => /home/nschelly/work/tmp
17:26 nschelly@serenity: ~/work/tmp$ vagrant destroy
    default: Are you sure you want to destroy the 'default' VM? [y/N] y
==> default: Forcing shutdown of VM...
==> default: Destroying VM and associated drives...
17:26 nschelly@serenity: ~/work/tmp$ rm -R *
17:26 nschelly@serenity: ~/work/tmp$ vagrant init --box-version 2.3.0 bento/ubuntu-14.04
A `Vagrantfile` has been placed in this directory. You are now
ready to `vagrant up` your first virtual environment! Please read
the comments in the Vagrantfile as well as documentation on
`vagrantup.com` for more information on using Vagrant.
17:26 nschelly@serenity: ~/work/tmp$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'bento/ubuntu-14.04' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: 2.3.0
==> default: Loading metadata for box 'bento/ubuntu-14.04'
    default: URL: https://atlas.hashicorp.com/bento/ubuntu-14.04
==> default: Adding box 'bento/ubuntu-14.04' (v2.3.0) for provider: virtualbox
    default: Downloading: https://atlas.hashicorp.com/bento/boxes/ubuntu-14.04/versions/2.3.0/providers/virtualbox.box
==> default: Successfully added box 'bento/ubuntu-14.04' (v2.3.0) for 'virtualbox'!
==> default: Importing base box 'bento/ubuntu-14.04'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'bento/ubuntu-14.04' is up to date...
==> default: Setting the name of the VM: tmp_default_1476307634103_74599
==> default: Fixed port collision for 22 => 2222. Now on port 2200.
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2200 (host) (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2200
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

Side note: The instructions for using the older boxes at https://atlas.hashicorp.com/bento/boxes/ubuntu-14.04 don't mention using the _--box-version_ option, and that kinda matters.

**Comment by chris-fa** [comment] 2016-10-13 02:42
By adding the following code, I'm able to bypass this error. **However**, it only works if I `vagrant destroy --force && vagrant up`.

If I `vagrant halt` or `vagrant reload --provision` or whatever, it doesn't. I have to kill the box and recreate it every time (which is very inconvenient as I am doing a Chef cookbook 😫 ).

```
  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
  end
```

**Comment by rickard-von-essen** [comment] 2016-10-13 12:26
Duplicates #688, see https://github.com/chef/bento/issues/688#issuecomment-252404560

**Comment by lhagemann** [comment] 2016-10-13 14:46
Every single "duplicate" of this issue is closed, but there is no fix, only workarounds.

**Comment by rmoriz** [comment] 2016-10-13 14:51
@lhagemann the fix is to upgrade VirtualBox OR to pick one of the workarounds. see https://github.com/chef/bento/issues/688#issuecomment-252404560

**Comment by neilschelly** [comment] 2016-10-13 14:52
The fix in #688 is to upgrade virtualbox to a version that is not in either the latest Debian Stable + Backports or the latest Ubuntu LTS + Updates releases. That leaves me only with workarounds for a bit.

**Comment by rmoriz** [comment] 2016-10-13 14:54
@neilschelly ping the Debian/Ubuntu package maintainers or build a custom package.

**Comment by neilschelly** [comment] 2016-10-13 14:59
Honestly, I've put in hours just to build an empty cookbook to try out ChefDK which defaults to trying to build with these boxes. Given there's no helpful error message output, this took a while to track down this far. That's a lousy introduction to trying out a new tool.

I recognize that VirtualBox has a bug, but that's a bug that your users will be dealing with. Calling the bug in Virtualbox and closing the ticket is a cop-out. The bug from a user's perspective is that I installed ChefDK freshly according to Chef's instructions, and that doesn't work in literally even the simplest use case. It has no useful error message to help you find those workarounds. We can check issues lists, and there are no open issues. That shouldn't be good enough.

**Comment by cheeseplus** [comment] 2016-10-14 05:37
I'm sorry you've had trouble getting started @neilschelly and the complicated frustrations of issues with an underlying tool.

Distro packaging is it's own dead horse that I enjoy flogging but for tools like Virtualbox and ChefDK using the distro repos is dubious at best - Virtualbox themselves provide apt/yum repos as well as direct downloads. Moreover the upgrade or workarounds in #688 are the fix - I have zero ability to fix upstream package management as as someone who has long dealt with that very hassle it simply is what it is and not something I can do much about.

Compounding the difficulty is that I have to try to keep up with latest of hypervisors and by the nature of the drivers, each version cut may only work with a narrow matrix of versions so we leverage Atlas' ability to version which at least gives folks the ability to point at a specific one in case latest doesn't fit with their hypervisor versions.

Lastly I'd like to point out that while test-kitchen utilizes bento boxes as a default, neither project is wholy owned or maintained by Chef. I am not compensated or tasked with maintaining these in any capacity, I do it because nobody else was doing it - this release took almost a week of working out the hypervisor kinks, vagrant issues, and testing across several different machines all of which I maintain myself.

I can re-open the issue but it doesn't change the physics I've outlined.

**Comment by cheeseplus** [comment] 2016-10-18 12:52
@lhagemann are you still having issues after a 5.1.6 upgrade?

**Comment by lhagemann** [comment] 2016-10-19 21:16
yes, vbox version 5.1.6 does not display the issue.

**Comment by cheeseplus** [comment] 2016-10-25 23:01
Closing this as originally reported issue has been confirmed closed.

**Closed by cheeseplus** 2016-10-25 23:01 UTC
Labels: Duplicate, virtualbox

**Comment by xamox** [comment] 2017-03-15 14:36
@chris-fa Thanks your solution worked for me, I wish they would just put that into the tutorial so I didn't waste an entire hour trying to just get my VM setup just to start learning chef.

**Comment by cheeseplus** [comment] 2017-03-15 14:42
@xamox the reason we don't but it into the tutorial is because it's a hack that is only needed because of an underlying . The issue is complicated because of all the dependencies involved and the testing matrix is too broad for us to test every permutation of everyone's software.

If using current versions of Vagrant, Virtualbox, and Bento this is not an issue. I'm locking this thread because we've answered this several times over.
