### ISSUE TITLE
Ubuntu 18.04 image fails to install ansible

### ISSUE THREAD

**Issue by Zharktas** [chef/bento#1201] opened 2019-06-14 10:27 UTC
Libssl has been updated and installing ansible fails without upgrading OS packages. Most likely this is fixed by rebuilding the box.

# Version:

Ubuntu bento-18.04 201812.27.0

# Environment:
Vagrant 2.2.4
Virtualbox 6.0.4

# Scenario:

Installing ansible through using provisioner ansible_local

# Steps to Reproduce:
Run the following commands:
```
vagrant init bento/ubuntu-18.04 --box-version 201812.27.0
vagrant up
vagrant ssh
sudo add-apt-repository ppa:ansible/ansible -y && sudo apt-get update -y -qq && sudo apt-get install -y -qq ansible
```

# Expected Result:
Ansible to be installed.
# Actual Result:

```
Setting up libssl1.1:amd64 (1.1.1-1ubuntu2.1~18.04.2) ...
Checking for services that may need to be restarted...done.
Checking for services that may need to be restarted...done.
Checking init scripts...
dpkg: error processing package libssl1.1:amd64 (--configure):
 installed libssl1.1:amd64 package post-installation script subprocess returned error exit status 10
Setting up python-enum34 (1.1.6-2) ...
dpkg: dependency problems prevent configuration of python-cryptography:
 python-cryptography depends on libssl1.1 (>= 1.1.1); however:
  Package libssl1.1:amd64 is not configured yet.

dpkg: error processing package python-cryptography (--configure):
 dependency problems - leaving unconfigured
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...No apport report written because the error message indicates its a followup error from a previous failure.

Setting up python-ipaddress (1.0.17-1) ...
Setting up python-setuptools (39.0.1-2) ...
Setting up python-jinja2 (2.10-1ubuntu0.18.04.1) ...
dpkg: dependency problems prevent configuration of libssl-dev:amd64:
 libssl-dev:amd64 depends on libssl1.1 (= 1.1.1-1ubuntu2.1~18.04.2); however:
  Package libssl1.1:amd64 is not configured yet.

dpkg: error processing package libssl-dev:amd64 (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of python-paramiko:No apport report written because the error message indicates its a followup error from a previous failure.

 python-paramiko depends on python-cryptography (>= 1.1); however:
  Package python-cryptography is not configured yet.

dpkg: error processing package python-paramiko (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of ansible:No apport report written because MaxReports is reached already

 ansible depends on python-paramiko; however:
  Package python-paramiko is not configured yet.
 ansible depends on python-cryptography; however:
  Package python-cryptography is not configured yet.

dpkg: error processing package ansible (--configure):
 dependency problems - leaving unconfigured
Processing triggers for libc-bin (2.27-3ubuntu1) ...No apport report written because MaxReports is reached already

Errors were encountered while processing:
 libssl1.1:amd64
 python-cryptography
 libssl-dev:amd64
 python-paramiko
 ansible
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by dominikzogg** [comment] 2019-06-14 15:15
i tried to build the image myself (looks good), but it's not working (kernel panic on vagrant up before the login mask)

**Comment by jaredk-beta** [comment] 2019-06-14 18:15
Seeing the same problem when attempting to upgrade the `libssl1.1` package. I was able to work around it by updating the vagrant box to Ubuntu 18.04.2, so a rebuild of the box would likely resolve this.

**Comment by dominikzogg** [comment] 2019-06-15 19:28
same happens also on a vagrant setup using chef, seems to be an issue which is bigger than only python package realated

**Comment by bmoe872** [comment] 2019-06-16 22:13
I'm seeing the same issue when trying to install python3-dev and/or postgres.

**Comment by Zharktas** [comment] 2019-06-17 06:28
As a work around you can run shell provisioner that upgrades the base packages before your actual provisioner.

```
config.vm.provision "shell", inline: "apt-get update && DEBIAN_FRONTEND=noninteractive apt-get -y -q -o 'Dpkg::Options::=--force-confdef' -o 'Dpkg::Options::=--force-confold' upgrade dist"
```

**Comment by Nklya** [comment] 2019-06-17 06:52
I just switched to `ubuntu/bionic64` vagrant box.

**Comment by dominikzogg** [comment] 2019-06-17 06:54
@Nklya the original box is less optimized and got a to small disc and is only available for virtualbox

**Comment by mgruner** [comment] 2019-06-17 08:26
I also see the kernel panic and opened another issue for this: https://github.com/chef/bento/issues/1202.

**Comment by mgruner** [comment] 2019-06-17 08:26
I also see the kernel panic and opened another issue for this: https://github.com/chef/bento/issues/1202.

**Comment by comay** [comment] 2019-06-17 16:07
This might have been caused by the following fix to `libssl1.1`

https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1832522

**Comment by cheeseplus** [comment] 2019-06-17 16:50
So this isn't really an issue with the box as such - all boxes are released as point in time releases so if you need to upgrade for certain packages it's best to do that in your own scripts/provisioning. Releasing new boxes does "fix" this but it's also not something that is specifically wrong with the build scripts themselves, just a symptom of bit rot of the existing images.

The issue with kernel problems is different and already being tracked.

**Comment by MasterOdin** [comment] 2019-06-17 21:55
What are the chances of seeing a release of an updated image in the near future (especially given the comment in https://github.com/chef/bento/issues/1191#issuecomment-492265828)?

**Comment by tas50** [comment] 2019-06-18 06:44
I'm currently building all the images, but it takes a while on hotel wifi.

**Comment by tmeneau** [comment] 2019-06-18 11:16
Ran into this a few days ago while fleshing out some Terraform AWS EC2 provisioners on Ubuntu 18.04, but then again yesterday with the Ubuntu 18.04 Bento box during a `kitchen-vagrant` test using the `salt_solo` provisioner. @comay looks to be right about the actual source of this new behavior.

The [OpenSSL launchpad already has a bug filed](https://bugs.launchpad.net/ubuntu/+source/openssl/+bug/1832919) which describes a precise workaround:

> [ WORKAROUND TO RECOVER YOUR SYSTEM ]
> 
> $ sudo dpkg-reconfigure libc6
> $ sudo dpkg --configure libssl1.1

The workaround certainly works; I was able to apply it to the Bento box by initializing the VM with the following before running anything else:

```
    sudo DEBIAN_FRONTEND=noninteractive apt-get update
    sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libssl1.1
    sudo dpkg-reconfigure libc6 
    sudo DEBIAN_FRONTEND=noninteractive dpkg --configure libssl1.1 
```

**Comment by Nklya** [comment] 2019-06-18 20:12
Looks like a couple of hours ago, the vagrant box was updated
https://app.vagrantup.com/bento/boxes/ubuntu-18.04

**Comment by cheeseplus** [comment] 2019-06-18 20:13
The full release is going out (but takes a while) according to the #bento channel in the Chef Community Slack.

**Comment by dominikzogg** [comment] 2019-06-18 20:24
the virtualbox image is working, thank you

**Comment by bmoe872** [comment] 2019-06-18 20:26
VMWare Box is working as well. Thank you!!!

**Closed** 2019-06-18 23:04 UTC
Labels: Status: Untriaged

**Comment by max-arnold** [comment] 2019-06-19 06:09
Any plans to update the Parallels box too? https://app.vagrantup.com/bento/boxes/ubuntu-18.04

**Comment by tas50** [comment] 2019-06-19 08:56
@max-arnold I’ll see if I can get those built later but right now I don’t have Parallels installed on my laptop

**Comment by pschiffe** [comment] 2019-07-04 17:09
Hey guys, I have the updated image `bento/ubuntu-18.04 (virtualbox, 201906.18.0)`, but still see this error:
```
dpkg: error processing package libssl1.1:amd64 (--configure):
  installed libssl1.1:amd64 package post-installation script subprocess returned error exit status 10
```
Can anyone confirm, or is it just me? Thanks.

**Comment by pschiffe** [comment] 2019-07-04 17:51
Forget about this ^ it was only me. After couple of more tries, it's working just fine for me now. Sorry.
