### ISSUE TITLE
Version 2.3.0 fails to connect network on VirtualBox

### ISSUE THREAD

**Issue by s2ugimot** [chef/bento#688] opened 2016-10-08 03:55 UTC
SSH timeouts when `vagrant up` with this version.
Network seems not to be configured correctly?

Open VirtualBox -> right click the Box base VM -> Open VM Configuration -> Network -> Adapter 1 -> "Cable connected" is not checked by default.

Reverted back to v2.2.9 solved the problem.

**Comment by rickard-von-essen** [comment] 2016-10-08 05:38
VirtualBox had a regression, which is fixed in:
- 5.1.6
- 5.0.28

See mitchellh/packer/issues/3757

Solutions (any of):
1) _Upgrade VirtualBox_ (recommended)
2) Downgrade your bento boxes to 2.2.9
3) Add the following to your `Vagrantfile`
```ruby
node.vm.provider 'virtualbox' do |vb|
        vb.customize ["modifyvm", :id, "--cableconnected1", "on"]
end
```

**Comment by montge** [comment] 2016-10-10 17:31
This also seems to be effecting kitchen (1.13.0)

**Comment by chris-fa** [comment] 2016-10-10 21:24
@montge Any fixes for kitchen?

**Comment by jpujari-cartera** [comment] 2016-10-11 20:25
For kitchen, you can use the `box` parameter under `driver` in kitchen.yml file to specify a different image. But the recommended VBOX upgrade solution should work for kitchen users too.

**Comment by cheeseplus** [comment] 2016-10-11 23:52
@chris-fa there is no fix for kitchen, kitchen is not broken - this has to do with the virtualbox version more than anything else.

Closing this one as it's answered and we've got 3 dupes.

**Comment by chris-fa** [comment] 2016-10-12 00:18
@rickard-von-essen I believe this doesn't work for a `vagrant reload --provision` (or at least it isn't working for me); However, it does work doing `vagrant destroy --force`  and then `vagrant up`

**Comment by chris-fa** [comment] 2016-10-13 21:52
@rickard-von-essen  I'm using virtual box `5.1.6` and using bento/centos7.2 version `2.2.9` and added  to my Vagrantfile `vb.customize ["modifyvm", :id, "--cableconnected1", "on"]`,  but it still hangs.  Should I delete some kind of cache or global configuration file or similar, so that it works?

**Comment by bgroff** [comment] 2016-10-13 22:12
I am also running VB 5.1.6 with the bento/ubuntu-16.04 box and am still running into the hanging on ssh issue. Also added the cableconnected1 option with no luck.

**Comment by chris-fa** [comment] 2016-10-14 12:30
@bgroff what about `vagrant halt` and `vagrant up`? Does it get past the hang or it gets stuck again? (like me 😭 )

**Comment by bgroff** [comment] 2016-10-14 14:24
@chris-fa Yes, a `vagrant halt` followed by a `vagrant up` hangs.

**Comment by chris-fa** [comment] 2016-10-14 15:28
@bgroff :(   I am working with chef, so every `vagrant up` after destroying is  12 mins provision RIP

**Comment by bgroff** [comment] 2016-10-14 17:24
Should this ticket be reopened? VB 5.1.6 does not fix this issue. Also as @chris-fa stated even if you add `vb.customize ["modifyvm", :id, "--cableconnected1", "on"]` to the Vagrantfile, a `vagrant halt` then `vagrant up` hangs on ssh auth.

**Comment by cheeseplus** [comment] 2016-10-14 22:16
So the issue is for 2.3.0 but the issues above reference 2.2.9 with 5.1.6 (which flips the problem the other way) - in the interest of sanity if folks could report the complete matrix of what they are considering broken.

Basically:
If using bento 2.3.0 then Virtualbox 5.1.6 and Vagrant 1.8.6 are required

If you're seeing that specific permutation fail then I'd like to get a repro case but I'm trying to separate some signal from noise here.

**Comment by chris-fa** [comment] 2016-10-17 13:11
@cheeseplus I tried with box 2.2.9 too, no luck. I then went back to `bento/centos-6.7` (version 2.2.7) and it worked. I couldnt find a way of making it work with `bento/centos-7.2`

**Comment by cheeseplus** [comment] 2016-10-17 13:15
In the interests of separating out precise problem, the condition is _only_ if you're doing a `vagrant halt` correct?

(Trying to stem cross-posting still)

**Comment by cheeseplus** [comment] 2016-10-17 14:18
Also what version of Vagrant?

**Comment by bgroff** [comment] 2016-10-17 14:34
I have to apologize for the noise. I thought I had upgraded to 5.1.6 which I had not. So please disregard my input for the moment.

**Comment by bradallenfisher** [comment] 2016-11-01 17:45
My issue was that on virtualbox 5.0.26 I could not run vagrant up with a clean init using bento/ubuntu-16.04. It had nothing to do with vagrant halt or reload. It was a fresh up. 

I can confirm that if you upgrade to virtualbox 5.1.8 bento/ubuntu-16.04 will get past the SSH auth method: private key hang. 

I can also confirm that the problem still exists if you only upgrade Virtual Box to 5.0.28.

Is this something that can be fixed in a later version of vagrant or should I put min versions on Virtual Box and Vagrants when people try to run our software?

**Comment by cheeseplus** [comment] 2016-11-01 17:52
As the person building bento I, by necessity have to lock down the versions of everything, because of unexpected regressions like we've seen here. On a fresh up, with no pre-existing vagrant box of the same name, it will fail as vagrant defaults to grabbing the latest off Atlas - this can be mitigated in your Vagrantfile by specifying a version and test-kitchen (via kitchen-vagrant) can do the same.

The issue here is trying to deal with upstream errors in several projects. This can't be fixed in Vagrant without HashiCorp testing every single new version of hypervisor and hard coding it in which would be an exercise in madness. So the aforementioned solutions are your best bet here @bradallenfisher - fwiw, 5.1.8 also has some serious regressions so we stuck with 5.1.6 across the board on bento until the situation improves.

**Comment by bradallenfisher** [comment] 2016-11-01 18:00
cool. Thanks @cheeseplus

**Comment by ferrarimarco** [comment] 2016-11-16 12:35
Hi everyone. I have the same issue on Virtualbox 5.1.8, using the 2.3.0 ubuntu 16.04 image.

Thanks

**Comment by cheeseplus** [comment] 2016-11-16 13:12
@ferrarimarco what version of Vagrant? We really need more detail on these postings as "me too" follow ups are often not actually the same root issues.

**Comment by ferrarimarco** [comment] 2016-11-16 13:14
@cheeseplus 1.8.6

**Comment by cheeseplus** [comment] 2016-11-16 13:27
@ferrarimarco what is the actual issue here? please post gist the detailed log and also make sure to remove any existing vagrant boxes and reimport as the importing function in 5.0.x was where one bug was as well.

**Comment by ferrarimarco** [comment] 2016-11-16 15:00
@cheeseplus  Here is the log. I followed your procedure. Thanks

[vagrant bento log.txt](https://github.com/chef/bento/files/594945/vagrant.bento.log.txt)

**Comment by wstaples** [comment] 2016-11-16 15:34
I'm having the same issue on Windows 7 64-bit, Vagrant 1.8.7 and VirtualBox 5.1.8. I was on virtualbox 5.0.something and I upgraded to see if it would resolve the issue. I went with the `--cableconnected1` solution and that has fixed it for me.

**Comment by cheeseplus** [comment] 2016-11-16 15:34
The timeout error, especially lately, has been from Vagrant itself or a buggy version of VirtualBox. I am unable to repro on a Windows 7 machine but the box is coming up normally on Linux and OSX workstations. 

Is there anything in your Vagrantfile that is messing with the key? more specifically is this only on a halt and power on or a true fresh `vagrant up`?

When we've seen this in the past it's almost always been something that wasn't installed or for whatever reason needed to be reinstalled wrt Vagrant or Vbox. There is potential it's a Windows specific issue in Vagrant (1.8.7) was just released but I've not heard anything on that front from folks who are using it daily.

**Comment by wstaples** [comment] 2016-11-16 15:50
If I open the Virtualbox console and show the gui I can see that the box is stuck on `start job is running for Raise network interfaces`. It has a timer and will stop after 5 minutes however vagrant throws a timeout error first. Another thing of note when I installed vbox 5.1.8 I had to use the `-msiparams NETWORKTYPE=NDIS5` which could also be a factor (and would explain why it works in linux).

**Comment by ferrarimarco** [comment] 2016-11-16 15:55
@cheeseplus I tried with a minimal Vagrant file (just the box, CPU and memory configuration) and it happened again.
I enabled the GUI and it shows the "Emergency mode" (see the attached screenshot).

Thanks

![image](https://cloud.githubusercontent.com/assets/621939/20354126/6ff56600-ac1d-11e6-8088-b9b7e756c104.png)

**Comment by cheeseplus** [comment] 2016-11-16 15:57
Could you please open a separate issue?

This is starting to sound different and more specific than the initial issue which many have reported as solved and this is why I was trying to avoid the pile on posts because the underlying causes are likely different here.

**Comment by ferrarimarco** [comment] 2016-11-16 16:03
@cheeseplus are you talking to me about the separate issue? If so, will do. no problem

**Comment by cheeseplus** [comment] 2016-11-16 16:06
Yes @ferrarimarco - this seems uniquely different and given @wstaples comments could be specific to Windows (plus whatever vagrant and vbox bugs exist)

**Comment by ferrarimarco** [comment] 2016-11-17 08:20
@cheeseplus done, #719 thanks

**Comment by cheeseplus** [comment] 2016-11-18 16:46
I'm going to close out this thread because we have solved for the initial report and some other issues appear specific to other conditions.

**Closed by cheeseplus** 2016-11-18 16:46 UTC
Labels: virtualbox

**Comment by remram44** [comment] 2016-12-20 22:51
> VirtualBox had a regression, which is fixed in:
> 
> 5.1.6
> 5.0.28

I'm having the issue on `5.0.30 r112061` (MacOS). `5.1.12 r112440` worked.

**Comment by cheeseplus** [comment] 2016-12-20 22:55
At this point we don't expect anything 5.0.x to work with bento.

**Comment by rutsky** [comment] 2017-01-25 14:00
Had the issue on currently default Virtualbox 5.0.24 version on Ubuntu 16.04.
Installing 5.0.32 from xenial-proposed on fixed the issue (should be released in 16.04.2).

**Comment by rmccue** [comment] 2017-06-09 03:10
Also experiencing this issue on the very latest of everything (Vagrant 1.9.5, VirtualBox 5.1.22, macOS 10.12). Is this another regression in VirtualBox?

**Comment by cheeseplus** [comment] 2017-09-25 19:58
That's a vbox regression @rmccue or you have an old bento box. I am locking this one as with others because most of these are old versions of upstream software I can't do anything about. If folks have similar problems, please open a new issue with all the version information and we can move from there.
