### ISSUE TITLE
Workstation 11.1.2 Tools incompatible with current builds

### ISSUE THREAD

**Issue by thasmo** [chef/bento#377] opened 2015-06-29 16:57 UTC
I've upgraded Workstation to version 11.1.2 on Windows and encountered problems with the current builds on Atlas. Vagrant wasn't able to create synced folders. After I had re-installed the VMware Tools manually it worked again. Seems like the currently installed Tools version is not compatible with Workstation 11.1.2.

**Comment by thasmo** [comment] 2015-06-29 22:17
The new Ubuntu 15.04 64-bit box works well. The problem occured when using the 14.10 64-bit box.

**Comment by thasmo** [comment] 2015-06-29 22:20
On a second try I also have the problem with 15.04. Weird.

**Comment by fnichol** [comment] 2015-06-30 19:33
Interesting, I wonder if VMware Workstation and VMware Fusion install different versions (or implementations) of VMware Tools.

Does this only happen for the older Ubuntu releases (like 14.10 as you mentioned), but not for 15.04 (aside from the Vagrant bug)? Currently the Atalas boxes haven't been rebuilt since their initial publish and therefore may have older VMware Tools installed. Getting more frequent/fresh builds is something we're working towards, but still a bit down the road (i.e. not next week kinda thing).

Looks like I should get a license for Workstion in the meantime though.

**Comment by fnichol** [comment] 2015-06-30 19:34
Adding the VMware Workstation 11.1.2 [release notes](https://www.vmware.com/support/ws/doc/workstation-1112-release-notes.html) for future reference,

**Comment by thasmo** [comment] 2015-06-30 20:01
Yes, as mentioned it seems the VMware Tools which are installed on the 15.04 box are compatible with Workstation 11.1.2. Problems occur with the 14.10 box.

**Comment by rfc1459** [comment] 2015-07-04 12:37
I just ran an Ubuntu 14.04 build on VMware Workstation and there's a serious issue with kernel package handling (which ultimately leads to this bug): essentially, the [update script](https://github.com/chef/bento/blob/00798d975dd6e28475925932acc34d234deb4d57/scripts/ubuntu/update.sh) does not take the LTS HWE packages into account, defaulting instead to `linux-server` and `linux-headers-server`. This causes the `-lts-utopic` packages (which are the ones brought in by the 12.04.2 installer) to be kept back.

Furthermore, the cleanup script brings in the kernel packages which should have been installed by the update phase: coupled with the fact that at this point the tools are installed already and the autoupdate feature is disabled this leads to a running kernel _without_ the relevant VMware modules built and installed.

I'm not entirely sure how to fix this without rewriting a large portion of the involved scripts, I'll try to give it a shot in the next few days.

**Comment by cheeseplus** [comment] 2015-08-27 01:42
We've rebuilt all the boxes @8a424e2900148bb8d732604844b4e18bce064d07 - is this still an issue? I don't have access to VMware workstation but of Fusion installs the updated tools this may have gone away.

**Comment by tisba** [comment] 2015-09-06 12:20
@cheeseplus I tried to use https://atlas.hashicorp.com/bento/boxes/ubuntu-14.04/versions/2.2.0 with VMware Fusion Version 8.0.0 (2985594) on OS X 10.10.5 but ran into the same problem: Vagrant hangs at `==> default: Waiting for HGFS kernel module to load...`.

**Comment by Einkoro** [comment] 2015-09-12 01:51
I'm seeing the same issue with VMware Fusion Version 8.0.0 on OS X 10.11 GM.

**Comment by thasmo** [comment] 2015-09-20 17:37
The latest version of the Ubuntu 15.04 box on Atlas, version 2.2.1 stopped working with VMware Workstation 11.1.2. Version 2.2.0 was working well with it. @fnichol, is this a known issue?

**Comment by cheeseplus** [comment] 2015-09-21 14:43
@thasmo so the 2.2.1 boxes were built with Fusion 8.0.0 but otherwise same templates (at least for Ubuntu). We haven't systematically tackled and tested all the permutations of tooling versions with operating systems yet - this seems to be further complicated by increasing Fusion and Workstation versions.

**Comment by thasmo** [comment] 2015-09-26 00:32
Ye, seems like every VMware update introduces the same problems over and over. Does #454 fix it?

**Comment by cheeseplus** [comment] 2015-09-26 18:07
@thasmo so from the testing I've done it does fix it for some value of fix - testing has only been done with Fusion 8 however as we do not currently have a VMware workstation license. That said the 2.2.2 boxes (not yet released) all seem to load the HGFS module fine and mounts the folders as intended. I'll be closing this issue once I release those boxes and any new issues that present we can troubleshoot against specific versions.

**Comment by thasmo** [comment] 2015-09-26 19:29
Sounds great!

**Comment by dilas** [comment] 2015-09-27 04:52
Or just use: https://github.com/rasa/vmware-tools-patches

Works nice on VMWare Fusion 7.1.2 and Debian 8.2.

**Comment by davidmnoriega** [comment] 2015-10-01 19:08
I'm running VMware Fusion 7 and when I built the ubuntu-14.04 box, the `--force-install` option doesn't exist.

**Comment by cheeseplus** [comment] 2015-10-02 09:17
@davidmnoriega supporting past versions is going to be difficult from an infrastructure standpoint - mostly because of the forced upgrades to support particular OSX revisions. That said we'll probably look at using the aformentioned project https://github.com/rasa/vmware-tools-patches to try to make this a little less onerous - just that testing all the permutations will still be difficult.

**Comment by cheeseplus** [comment] 2015-10-07 19:30
Closing this as fixed efeb14a810551b06d7c5718639034cd9d3b45219

That said I do not expect this to fix all the problems in this thread but these need to be opened as individual issues with the as many version specifics as possible i.e. packer, VMware Fusion/Workstation Version, host OS, bento artifact OS.

**Closed by cheeseplus** 2015-10-07 19:30 UTC
Labels: Bug, Triaged
