### ISSUE TITLE
ssh.insert_key in centos-7.1 and centos-7.2 boxes vagrant provider= vmware_fusion

### ISSUE THREAD

**Issue by SierraX369** [chef/bento#641] opened 2016-08-01 07:36 UTC
Hi bento team,

have an issue tested on centos-7.1 and centos-7.2 boxes.
The insecure_public_key will replaced by vagrant, but the file-permissions of /home/vagrant/.ssh/authorized_keys then set to 664. A login is only possible with file-permissions 600.
Maybe a umask problem.
I use right now the workaround, to start the machine with 'config.ssh.insert_key=false' and replace the authorized_keys by hand.

Kind Regards
SierraX369

**Comment by rickard-von-essen** [comment] 2016-08-01 07:42
See https://github.com/mitchellh/vagrant/pull/7611

**Comment by SierraX369** [comment] 2016-08-01 07:42
Sorry forgot my setup:
vmware-fusion = 8.1.1 (3771013)
vagrant = 8.1.5
plugin:
vagrant-vmware-fusion = 4.0.10

**Comment by legal90** [comment] 2016-08-01 08:13
As @rickard-von-essen has mentioned above, that's the known issue of Vagrant 1.8.5 (https://github.com/mitchellh/vagrant/pull/7610), which was already fixed in vagrant's master branch by https://github.com/mitchellh/vagrant/pull/7611.

This issue is reproducible for all RHEL-based Linux guests and all providers with Vagrant 1.8.5.
We are looking forward to Vagrant 1.8.6 with the fix being released soon. Currently you can work it around by downgrading to Vagrant v1.8.4: https://releases.hashicorp.com/vagrant/1.8.4/

I'm gonna close this, since there is nothing to do on the Bento's side.

**Closed by legal90** 2016-08-01 08:13 UTC
