### ISSUE TITLE
Ubuntu: grub-pc forces non-interactive apt-get upgrade

### ISSUE THREAD

**Issue by felicianotech** [chef/bento#661] opened 2016-09-19 18:32 UTC
Running `sudo apt-get -y update && sudo apt-get -y upgrade` stops on the screen to reconfigure Grub due to "The GRUB boot loader was previously installed to a disk that is no longer present". This breaks my provisioning script.

Running:
- Vagrant v1.8.5
- Virtualbox v5.1.6
- Box: bento/ubuntu-16.04 v2.2.9

This is what comes up (grub-pc):
![grub-config](https://cloud.githubusercontent.com/assets/6017470/18645035/9bfd2a2a-7e79-11e6-9f07-53e90a92cf51.png)

**Comment by cheeseplus** [comment] 2016-09-19 18:45
Could you provide a bit more detail here?

- which box and which version?
- is this a command you're running yourself after brining up a box?

**Comment by felicianotech** [comment] 2016-09-19 18:47
The bento/ubuntu-16.04 box latest version (v2.2.9). This happens when I use a bootstrap.sh provisioning script, or when I SSH in using `vagrant up` and run apt-get update and apt-get upgrade manually.

**Comment by samholmes1337** [comment] 2016-09-19 21:32
I can confirm this is happening to me as well. This is what my vagrantfile looks like:

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "bento/ubuntu-16.04"
  config.vm.provision :shell, inline: "apt-get -y update && apt-get -y upgrade"

  config.vm.define "cm1" do |cfg|
    cfg.vm.hostname = "cm1"
    cfg.vm.provider "virtualbox" do |vb|
      vb.name = "cm1"
    end
  end

end
```

And when I run `vagrant up` my vagrant bootstrap gets stuck on this:

<img width="675" alt="screen shot 2016-09-19 at 22 31 29" src="https://cloud.githubusercontent.com/assets/8385528/18649704/df675530-7eb8-11e6-9e57-9df300077fc4.png">

Which appears to be a `stdout` version of what @felicianotech saw.

**Comment by samholmes1337** [comment] 2016-09-19 21:43
Okay so I have found a good temporary workaround to this problem [on this stackoverflow answer](http://askubuntu.com/questions/146921/how-do-i-apt-get-y-dist-upgrade-without-a-grub-config-prompt). Instead of having `apt-get -y upgrade`, you can use `DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade` which forces `apt` to be fully non-interactive. Still a frustrating workaround and would be good to have a fix for this (probably just by making sure the base box uses/installs/configures `grub` correctly).

**Comment by samholmes1337** [comment] 2016-09-21 13:23
@cheeseplus I believe the public box would simply need updating to the latest version of grub (re-running the build script should do it, as far as I can tell). Is something that would be possible?

**Comment by cheeseplus** [comment] 2016-09-21 16:36
We normally update the boxes when changes have been made and to keep up with updates - the catch here is that the box itself, seems fine - it's when you do following operations where grub gets updated. What probably needs to happen is to find the root cause of where grub is looking for the disk and see if we can solve for that.

**Comment by kylegoch** [comment] 2016-09-28 15:02
I am seeing this on bento/ubuntu-14.04 (2.2.9) when running `apt-get upgrade` as well.

**Comment by cheeseplus** [comment] 2016-10-02 12:37
Rolled out 2.3.0 - this should resolve the issue though I'm not sure what actually caused it in the first place.

**Comment by felicianotech** [comment] 2017-01-14 17:36
@cheeseplus This issue has resurfaced. :/

**Comment by Oscarteg** [comment] 2017-01-16 09:20
Same issue here

**Comment by toddprater** [comment] 2017-01-16 16:43
Same

**Comment by cheeseplus** [comment] 2017-01-17 17:16
I'm alright to re-open this but the issue appears to be one of grub on Ubuntu and in all cases that I've read the solution is to just tell apt-get upgrade to be quiet a la https://github.com/chef/bento/issues/661#issuecomment-248136601

This isn't to say we won't address this in an underlying way if possible but I'm not entirely sure we have any control other than just churning out new boxes to stay ahead of the issue.

**Comment by tisba** [comment] 2017-02-23 10:23
@sam3d: Thanks for your workaround in https://github.com/chef/bento/issues/661#issuecomment-248136601!

**Comment by Niemzok** [comment] 2017-07-07 13:13
I got the same issue here..

**Comment by twhetzel** [comment] 2017-07-07 22:03
@Niemzok - please post any issues to the Udacity discussion forums. Thanks!

**Comment by sam3d** [comment] 2017-07-08 14:01
@Niemzok have you tried the workaround I posted further up? It's weird that this issue keeps resurfacing.

That said, if you're creating a non-interactive script I've since realised it _is_ standard practice to set `DEBIAN_FRONTEND` env variable to `noninteractive` and add the other apt flags to ensure the script will complete without a hitch.

**Comment by cheeseplus** [comment] 2017-08-25 20:22
So after staring this one down for a while this only manifests if you actually run those commands via shell or whatever yourself without those flags set which any automation framework will do as a matter of course. As such I'm closing this issue because the boxes themselves aren't in any way broken or misconfigured, the process by which folks were running update/upgrade was not "correct".

**Closed by cheeseplus** 2017-08-25 20:22 UTC

**Comment by felicianotech** [comment] 2017-08-28 22:56
So what is considered the correct way?

Using @sam3d's Vagrantfile example above, I tried using:

`DEBIAN_FRONTEND=noninteractive apt-get -y update && apt-get -y upgrade`

and the issue still happens (using the 2.3.9 version of this box). Not to mention that this issue never happened with the `ubuntu/trusty` box. I tried moving over to `bento/ubuntu-16.04` instead of `ubuntu/xenial` simply because Canonical stopped maintaining their box.

**Comment by sam3d** [comment] 2017-08-28 23:15
@felicianotech Have you tried adding the additional `Dpkg::` flags?

It should be `DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade`.

**Comment by Mahmoud126** [comment] 2017-11-07 14:24
import psycopg2

def get_top_articles():
   db = psycopg2.connect("dbname=news")
   c = db.cursor()
   c.execute("select title from articles")
   return c.fetchall()
   db.close()

if _name_ == "__main__":
 print("THE LIST OF POPULAR ARTICLES ARE:")
 get_top_articles()
and get this error 
THE LIST OF POPULAR ARTICLES ARE:
Traceback (most recent call last):
 File "C:\Users\ATHE\Desktop\udacity\vagrant\logs_analysisdb.py", line 12, in <module>
   get_top_articles()
 File "C:\Users\ATHE\Desktop\udacity\vagrant\logs_analysisdb.py", line 4, in get_top_articles
   db = psycopg2.connect("dbname=news")
 File "C:\Users\ATHE\AppData\Local\Programs\Python\Python36\lib\site-packages\psycopg2\__init__.py", line 130, in connect
   conn = _connect(dsn, connection_factory=connection_factory,
how to solve this error

**Comment by mcm-jyl** [comment] 2018-01-02 16:27
@sam3d, absolutely, 
    `config.vm.provision :shell, inline: 'DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade'`
works fine (BTW, proper solution on the way apparently).
Thanks.

**Comment by wheelerlaw** [comment] 2018-01-30 03:00
Just tried `DEBIAN_FRONTEND=noninteractive sudo apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install --only-upgrade grub-pc`, and I was still prompted with the Grub configuration screen.

**Comment by cheeseplus** [comment] 2018-01-30 03:16
The command should be `upgrade` but also this issue has meandered enough and none of these have been issues addressable in the base box as this is purely the nature of running those commands with shell provisioners without the proper incantations. If anything it's the upstream distro's issue and so I'm locking this one because it needs to be be put to bed.
