### ISSUE TITLE
bento/ubuntu-20.04 apt failure

### ISSUE THREAD

**Issue by hutcj** [chef/bento#1306] opened 2020-09-01 18:04 UTC
# Version:

bento/ubuntu-20.04 v202008.16.0

# Environment:

Windows 10 2004
Vagrant 2.2.10
VirtualBox 6.1.12 r139181

# Scenario:

Start the Ubuntu VM with vagrant and use the apt package manager.

# Steps to Reproduce:

Using this Vagrantfile:
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "bento/ubuntu-20.04"
end
```

Run:
```
vagrant up
vagrant ssh
sudo apt-get update
```

# Expected Result:

I would expect to see normal apt messages. For example, this is what it looks like in bento/ubuntu-18.04:
```
vagrant@vagrant:~$ sudo apt-get update
Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Get:4 http://security.ubuntu.com/ubuntu bionic-security/main i386 Packages [522 kB]
Get:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [1,052 kB]
Get:7 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [818 kB]
Get:8 http://security.ubuntu.com/ubuntu bionic-security/main Translation-en [257 kB]
Get:9 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [77.1 kB]
Get:10 http://security.ubuntu.com/ubuntu bionic-security/restricted Translation-en [16.9 kB]
Get:11 http://security.ubuntu.com/ubuntu bionic-security/universe i386 Packages [635 kB]
Get:12 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [696 kB]
Get:13 http://archive.ubuntu.com/ubuntu bionic-updates/main i386 Packages [732 kB]
Get:14 http://security.ubuntu.com/ubuntu bionic-security/universe Translation-en [230 kB]
Get:15 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [8,312 B]
Get:16 http://security.ubuntu.com/ubuntu bionic-security/multiverse Translation-en [2,880 B]
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/main Translation-en [351 kB]
Get:18 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [89.9 kB]
Get:19 http://archive.ubuntu.com/ubuntu bionic-updates/restricted Translation-en [19.6 kB]
Get:20 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1,103 kB]
Get:21 http://archive.ubuntu.com/ubuntu bionic-updates/universe i386 Packages [1,028 kB]
Get:22 http://archive.ubuntu.com/ubuntu bionic-updates/universe Translation-en [343 kB]
Get:23 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [19.4 kB]
Get:24 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse Translation-en [6,740 B]
Fetched 8,261 kB in 10s (853 kB/s)
Reading package lists... Done
```

# Actual Result:

This is what happens when running apt in bento/ubuntu-20.04 (similar errors for `apt-get install <package>`):
```
vagrant@vagrant:~$ sudo apt-get update
Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [107 kB]
Hit:2 http://archive.ubuntu.com/ubuntu focal InRelease
Get:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease [111 kB]
Get:4 http://security.ubuntu.com/ubuntu focal-security/main i386 Packages [66.3 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal-backports InRelease [98.3 kB]
Get:6 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [171 kB]
Get:7 http://archive.ubuntu.com/ubuntu focal-updates/main i386 Packages [202 kB]
Get:8 http://security.ubuntu.com/ubuntu focal-security/main Translation-en [61.7 kB]
Err:6 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages
  Hash Sum mismatch
  Hashes of expected file:
   - Filesize:1115009 [weak]
   - SHA256:dabf5a1739b1e6a671c442c8e73eff157651acb34a795397251386a941bf5ea1
   - SHA1:bc5cf448ed377b296c4da959ffff65abfe7a34a2 [weak]
   - MD5Sum:e3fdb42c041348d455472a0178f3ec34 [weak]
  Hashes of received file:
   - SHA256:19491752ea189dc4320f95b14a52e6884a0a7837c047112b378ca9904c81e8ee
   - SHA1:c97d34ba0ce192741789ef5a0d896156910ae8cb [weak]
   - MD5Sum:e3fdb42c041348d455472a0178f3ec34 [weak]
   - Filesize:1115009 [weak]
  Last modification reported: Tue, 01 Sep 2020 13:08:01 +0000
  Release file created at: Tue, 01 Sep 2020 16:42:13 +0000
Get:9 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [341 kB]
Get:10 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [31.7 kB]
Err:7 http://archive.ubuntu.com/ubuntu focal-updates/main i386 Packages
  Hash Sum mismatch
  Hashes of expected file:
   - Filesize:1302077 [weak]
   - SHA256:c58c8cba2b262fb85c1301ed582e2dde433a49a1f005515c0c5d845c8b3bee80
   - SHA1:8252d0cedf86486c1ffdcd1340735dd4672b426a [weak]
   - MD5Sum:3b6885834e64574e2ceb973cc36346ca [weak]
  Hashes of received file:
   - SHA256:f9471777ac78ce0be6e3b8046b8667766a013693daf91a33b30643f3ab46c94f
   - SHA1:5d7ede99987ebadf47c270c91ae3457053d31a4f [weak]
   - MD5Sum:3b6885834e64574e2ceb973cc36346ca [weak]
   - Filesize:1302077 [weak]
  Last modification reported: Tue, 01 Sep 2020 15:56:10 +0000
  Release file created at: Tue, 01 Sep 2020 16:42:25 +0000
Get:11 http://security.ubuntu.com/ubuntu focal-security/restricted Translation-en [8,312 B]
Get:12 http://security.ubuntu.com/ubuntu focal-security/universe i386 Packages [26.1 kB]
Get:13 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [55.1 kB]
Get:14 http://security.ubuntu.com/ubuntu focal-security/universe Translation-en [28.4 kB]
Get:15 http://archive.ubuntu.com/ubuntu focal-updates/main Translation-en [129 kB]
Get:16 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [31.8 kB]
Get:17 http://archive.ubuntu.com/ubuntu focal-updates/restricted Translation-en [8,340 B]
Get:18 http://archive.ubuntu.com/ubuntu focal-updates/universe i386 Packages [88.7 kB]
Get:19 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [163 kB]
Get:20 http://archive.ubuntu.com/ubuntu focal-updates/universe Translation-en [82.0 kB]
Fetched 1,812 kB in 3s (559 kB/s)
Reading package lists... Error!
E: Failed to fetch store:/var/lib/apt/lists/partial/security.ubuntu.com_ubuntu_dists_focal-security_main_binary-amd64_Packages.xz  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:1115009 [weak]
    - SHA256:dabf5a1739b1e6a671c442c8e73eff157651acb34a795397251386a941bf5ea1
    - SHA1:bc5cf448ed377b296c4da959ffff65abfe7a34a2 [weak]
    - MD5Sum:e3fdb42c041348d455472a0178f3ec34 [weak]
   Hashes of received file:
    - SHA256:19491752ea189dc4320f95b14a52e6884a0a7837c047112b378ca9904c81e8ee
    - SHA1:c97d34ba0ce192741789ef5a0d896156910ae8cb [weak]
    - MD5Sum:e3fdb42c041348d455472a0178f3ec34 [weak]
    - Filesize:1115009 [weak]
   Last modification reported: Tue, 01 Sep 2020 13:08:01 +0000
   Release file created at: Tue, 01 Sep 2020 16:42:13 +0000
E: Failed to fetch store:/var/lib/apt/lists/partial/archive.ubuntu.com_ubuntu_dists_focal-updates_main_binary-i386_Packages.xz  Hash Sum mismatch
   Hashes of expected file:
    - Filesize:1302077 [weak]
    - SHA256:c58c8cba2b262fb85c1301ed582e2dde433a49a1f005515c0c5d845c8b3bee80
    - SHA1:8252d0cedf86486c1ffdcd1340735dd4672b426a [weak]
    - MD5Sum:3b6885834e64574e2ceb973cc36346ca [weak]
   Hashes of received file:
    - SHA256:f9471777ac78ce0be6e3b8046b8667766a013693daf91a33b30643f3ab46c94f
    - SHA1:5d7ede99987ebadf47c270c91ae3457053d31a4f [weak]
    - MD5Sum:3b6885834e64574e2ceb973cc36346ca [weak]
    - Filesize:1302077 [weak]
   Last modification reported: Tue, 01 Sep 2020 15:56:10 +0000
   Release file created at: Tue, 01 Sep 2020 16:42:25 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
E: Encountered a section with no Package: header
E: Problem with MergeList /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_focal_universe_binary-amd64_Packages
E: The package lists or status file could not be parsed or opened.
```

Also, I noticed that net-tools is not installed on bento/ubuntu-20.04 like it is on previous boxes (e.g. can't run ifconfig, netstat, etc.). Is there a reason for this difference or is it related to this issue with apt?

**Comment by tas50** [comment] 2020-10-14 17:03
@hutcj Can you try pulling down the new Ubuntu 20.04 box and trying again. I've rebuilt it using the latest and greatest.

**Comment by hutcj** [comment] 2020-10-14 20:56
Updating box versions:

```
$ vagrant box update
==> default: Checking for updates to 'bento/ubuntu-20.04'
    default: Latest installed version: 202008.16.0
    default: Version constraints:
    default: Provider: virtualbox
==> default: Updating 'bento/ubuntu-20.04' with provider 'virtualbox' from version
==> default: '202008.16.0' to '202010.14.0'...
==> default: Loading metadata for box 'https://vagrantcloud.com/bento/ubuntu-20.04'
==> default: Adding box 'bento/ubuntu-20.04' (v202010.14.0) for provider: virtualbox
    default: Downloading: https://vagrantcloud.com/bento/boxes/ubuntu-20.04/versions/202010.14.0/providers/virtualbox.box
Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
    default:
==> default: Successfully added box 'bento/ubuntu-20.04' (v202010.14.0) for 'virtualbox'!
```

However, the issue with apt persists.

**Comment by tas50** [comment] 2020-10-22 02:41
I've pulled the latest box with the latest vagrant / virtualbox and I can't reproduce the error. Whatever bad config was on the Ubuntu servers or bad config in the image is resolved with the new image:

```vagrant@vagrant:~$ sudo apt-get update
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [107 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease [111 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease [98.3 kB]
Get:5 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [618 kB]
Get:6 http://archive.ubuntu.com/ubuntu focal-updates/main i386 Packages [354 kB]
Get:7 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [673 kB]
Get:8 http://archive.ubuntu.com/ubuntu focal-updates/universe i386 Packages [507 kB]
Fetched 2,469 kB in 2s (1,095 kB/s)
Reading package lists... Done```

**Closed by tas50** 2020-10-22 02:41 UTC
Labels: Status: Waiting on Contributor
