### ISSUE TITLE
VMware: HGFS not working - Ubuntu 14.04 2.2.5

### ISSUE THREAD

**Issue by ayanich** [chef/bento#556] opened 2016-04-01 17:47 UTC
vmware 8.1 + ubuntu 14.04 v2.2.5  - i tested this build and it still hangs on HFGS kernel module
```
==> default: Waiting for HGFS kernel module to load...
The HGFS kernel module was not found on the running virtual machine.
This must be installed for shared folders to work properly. Please
install the VMware tools within the guest and try again. Note that
the VMware tools installation will succeed even if HGFS fails
to properly install. Carefully read the output of the VMware tools
installation to verify the HGFS kernel modules were installed properly.
```

**Comment by cheeseplus** [comment] 2016-04-01 17:48
Opened this one just a few seconds after I opened one - renamed for clarity.

**Comment by moonglum** [comment] 2016-04-24 11:38
Yep, Ubuntu 14.04 v2.2.3 is working fine with HGFS. Is there any way to help find the problem?

**Comment by cheeseplus** [comment] 2016-04-26 22:56
@moonglum what kernel does 2.2.3 report?

This is probably going back to issues with HWE and the way around that is to start off with an older ISO and dist-upgrade.

**Comment by moonglum** [comment] 2016-04-29 18:01
@cheeseplus Here is the output for `uname -a`

```
Linux vagrant 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by cheeseplus** [comment] 2016-04-29 18:40
@moonglum so this is what I expected - this is very much related to https://github.com/chef/bento/issues/529. When you grab the latest 14.04 ISO they do you the courtesy of upgrading your kernel for hardware compatibility purposes. In order to get a non-HWE kernel you have to use an older ISO and upgrade from it.

**Comment by moonglum** [comment] 2016-04-29 19:43
Upgrading with dist-upgrade, right?

**Comment by cheeseplus** [comment] 2016-04-29 20:34
Correct, the deb-ish distros do dist-upgrade - it's just that if you start with 14.04.3 you'll get HWE even if you don't want it.

**Comment by cheeseplus** [comment] 2016-04-29 21:14
Correct, the deb-ish distros do dist-upgrade - it's just that if you start with 14.04.2 you'll get HWE even if you don't want it.

https://wiki.ubuntu.com/Kernel/LTSEnablementStack

**Comment by davidmnoriega** [comment] 2016-05-23 00:36
Just tested the new 2.2.7 release and its working.

**Comment by cheeseplus** [comment] 2016-05-23 01:11
Closing!

**Closed by cheeseplus** 2016-05-23 01:11 UTC
Labels: vmware

**Comment by moonglum** [comment] 2016-05-23 06:11
Yeha! Thank you :)

**Comment by geerlingguy** [comment] 2016-05-27 03:49
Hmm... is there any way to get it working on 16.04? We don't have the option of rolling back to any kernel older than the one in 16.04[.0] :/

**Comment by davidmnoriega** [comment] 2016-05-27 06:22
The issue is that the kernel module is not compatible with the newer
kernels, vmware now recommends using openvm tools instead. That package
includes the functionality as a fuse module, but vagrant's vmware plugin
only looks for the kernel module. See
https://github.com/mitchellh/vagrant/issues/6775
