### ISSUE TITLE
debian 8.1 processing had stopped on login screen 

### ISSUE THREAD

**Issue by a93ushakov** [chef/bento#422] opened 2015-08-17 10:26 UTC
`packer build --colors=true debian-8.1-i386.json` command installs debian in virtualbox.
As I understand it will finish all work and halt vitualbox without user actions, right?

I halt virtualbox (`sudo poweroff`), but last packer message is
`==> virtualbox-iso: Waiting for SSH to become available... `

`vagrant global-status` shows that there isn't any vagrant box.

**Comment by rickard-von-essen** [comment] 2015-08-17 12:25
It should build a vagrant box. If it is no progress while waiting for SSH there is a problem. Rerun with [packer debug enabled](http://packer.io/docs/other/debugging.html) and gist the log.

**Comment by a93ushakov** [comment] 2015-08-17 14:23
I execute 
```sh
PACKER_LOG=1 packer build --color=true --only=virtualbox-iso debian-8.1-i386.json 2> bento-errors.txt
```

bento-errors.txt content is:
http://pastebin.com/BcXJjKLW

**Comment by a93ushakov** [comment] 2015-08-17 16:29
ubuntu 15.04 server - the same error.

**Comment by cheeseplus** [comment] 2015-08-19 16:29
@a93ushakov this sounds like something specific to your environment / networking - I am building all of these just fine across several different hosts.

**Comment by a93ushakov** [comment] 2015-08-19 18:17
@cheeseplus I use Linux Mint 17.2 64 bit, Virtualbox 5.x.x.
I test bento on localhost.

Can problem be caused by the newer version of virtualbox?

**Comment by cheeseplus** [comment] 2015-08-19 18:32
@a93ushakov it could be caused by that - also it'd be helpful to get the version of packer you are using

The build pipeline I am building to automate this is currently using:
OS X 10.10
Packer 0.8.5
VirtualBox 4.3.30

I haven't upgraded the pipeine to 5.0.2 just yet so I could test issues against both versions.

**Comment by cheeseplus** [comment] 2015-08-20 18:32
@a93ushakov so I've update to VirtualBox 5.0.2 on the builders and still don't seem to encounter this issue.

**Comment by a93ushakov** [comment] 2015-08-20 19:09
@cheeseplus What command did you execute? Like
`packer build --color=true --only=virtualbox-iso debian-8.1-i386.json`
?

**Comment by cheeseplus** [comment] 2015-08-20 21:38
The build scripts use:

packer build #{template}.json

(this builds on virtualbox, fusion, and parallels)

**Comment by a93ushakov** [comment] 2015-08-21 03:56
I had pulled new changes in repo and try build again.
Process again stopped at that 
![debian-8 1-i386 running - oracle vm virtualbox_001](https://cloud.githubusercontent.com/assets/13286493/9401026/9874a840-47d1-11e5-84b7-0ea0ffb3dda5.png)

**Comment by andy-dufour** [comment] 2015-08-21 04:56
Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: a93ushakovSent: Thursday, August 20, 2015 11:56 PMTo: chef/bentoReply To: chef/bentoSubject: Re: [bento] debian 8.1 processing had stopped on login screen  (#422)I had pulled new changes in repo and try build again.
Process again stopped at that 


—Reply to this email directly or view it on GitHub.

**Comment by andy-dufour** [comment] 2015-08-21 04:58
Sorry, mis sent a blank reply after reading your email!                                                                                                                                                                                                                                                                                                                                         Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: a93ushakovSent: Thursday, August 20, 2015 11:56 PMTo: chef/bentoReply To: chef/bentoSubject: Re: [bento] debian 8.1 processing had stopped on login screen  (#422)I had pulled new changes in repo and try build again.
Process again stopped at that 


—Reply to this email directly or view it on GitHub.

**Comment by cheeseplus** [comment] 2015-08-28 22:02
I'm still unable to trace this to anything specific to in the bento templates themselves:

Can you create anything else with packer?
Is Virtualbox functioning normally?

**Comment by cheeseplus** [comment] 2015-09-08 19:49
Closing this due to non-response and unable to reproduce in any environment. Feel free to re-open with more specific detail.

**Closed by cheeseplus** 2015-09-08 19:49 UTC
Labels: Question, Triaged
