### ISSUE TITLE
vbox: Ubuntu 16.04 (Inappropriate ioctl for device)

### ISSUE THREAD

**Issue by SebTM** [chef/bento#665] opened 2016-09-23 15:42 UTC
Hello,

i still get "==> default: mesg: ttyname failed: Inappropriate ioctl for device" everytime vagrant starts a provision-script. I have the latest vagrant-version 1.8.5 on Mac OS X El Capitan.

Can I solve this?

Thanks!

**Comment by cheeseplus** [comment] 2016-09-23 15:49
Hello,

We're going to need a bit more detail to assist here. That bug, iirc, was related to issues with a specific Vagrant version. Perhaps you could post a bit more complete log and provider the version of the box you are using (`vagrant box list`).

**Comment by SebTM** [comment] 2016-09-23 17:19
Hello,

i will do my best to give you more informations. The message comes up everytime like this:

> ==> default: Running provisioner: shell...
>     default: Running: /var/folders/6t/nvkxb1yx0xd9hdwh2jc0zm2m0000gn/T/vagrant-shell20160923-4668-3p1dbo.sh
> ==> default: mesg: ttyname failed:
> ==> default: Inappropriate ioctl for device

But it is unrealted to the provision shell-script because it happend everytime on every script!

> ~ vagrant box list
> bento/ubuntu-16.04 (virtualbox, 2.2.9)

I installed it today. Can you tell me which other logs you need and where to find them?

**Comment by cheeseplus** [comment] 2016-09-23 18:38
What version of virtualbox and vagrant please? (just to verify the CLI output as vbox doesn't always uninstall properly)

**Comment by SebTM** [comment] 2016-09-23 18:56
> ~ VBoxManage --version
> 5.1.6r110634

> ~ vagrant --version
> Vagrant 1.8.5

Latest virtualbox-extension is also installed.

**Comment by cheeseplus** [comment] 2016-10-02 12:35
Try with the latest boxes (2.3.0) which is built with Vbox 5.1

**Comment by SebTM** [comment] 2016-10-05 16:33
Sometimes in this "format":

> ==> default: mesg:
> ==> default: ttyname failed
> ==> default: :
> ==> default: Inappropriate ioctl for device

**Comment by cheeseplus** [comment] 2016-10-09 04:31
Have you tried upgrading to vagrant 1.8.6? I'm not sure what the other error has to do with this if anything.

**Comment by SebTM** [comment] 2016-10-11 21:15
Thx for your reply. Upgrading to vagrant 1.8.6 did not change this. I will have a look at the second part soon.

**Comment by PlugIN73** [comment] 2016-10-26 14:54
Have this issue too on MacOS X Sierra
```
MacBook-Pro-user:bento plugin73$ vagrant box list
bento/ubuntu-16.04 (virtualbox, 2.3.0)

MacBook-Pro-user:bento plugin73$ vagrant version
Installed Version: 1.8.6
Latest Version: 1.8.6

MacBook-Pro-user:bento plugin73$ VBoxManage --version
5.1.8r111374
```

This is log of vagrant up:

```
ERROR vagrant: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

set -e
mkdir -p /vagrant
mount -o vers=3,udp 192.168.139.1:/Users/plugin73/vagrant/hexlet-box/bento /vagrant
if command -v /sbin/init && /sbin/init --version | grep upstart; then
  /sbin/initctl emit --no-wait vagrant-mounted MOUNTPOINT=/vagrant
fi

Stdout from the command:

Stderr from the command:

mesg: ttyname failed: Inappropriate ioctl for device
mount.nfs: Connection timed out
```

**Comment by SebTM** [comment] 2016-10-26 16:08
Hmm, I had this sometimes when destroying-vm and provision it again. It seems that "exports" under "/etc/exports" were not cleared correctly. After removing anything from there and rebooting my mac it works again.

I don't think your "mesg: ttyname failed: Inappropriate ioctl for device" is related to the nfs error.

**Comment by PlugIN73** [comment] 2016-10-26 16:35
@SebTM thank you! I just cleaned /etc/exports on my mac and restart it. After I tried to start vagrant and it stucked yet with the same logs...

**Comment by cheeseplus** [comment] 2016-10-26 22:51
So can I consider this closed as it's external to bento?

**Comment by PlugIN73** [comment] 2016-10-27 07:42
I think, my issue consider to vagrant 1.8.6 because after I reverted it to 1.8.5 and reinit my box I can't replay it. Thanx all!

**Comment by SebTM** [comment] 2016-10-27 09:31
@cheeseplus I can't test at the moment if the problem is solved by downgrading vagrant

**Comment by cheeseplus** [comment] 2016-12-16 17:14
Closing this one as it doesn't seem specific to the bento boxes, more vagrant configuration and NFS. Feel free to open another issue if it's something specific to a bento build.

**Closed by cheeseplus** 2016-12-16 17:14 UTC

**Comment by chaim-sw** [comment] 2017-01-11 22:26
Funny, Vagrant says just the opposite. https://github.com/mitchellh/vagrant/issues/7155

**Comment by richard-scott** [comment] 2017-01-24 10:25
I think this is an Ubuntu 'feature' and not a problem with Vagrant/VirtualBox/Bento. 
I fix it in my Vagrantfile with this:
```
  config.vm.provision "fix-no-tty", type: "shell" do |s|
    s.privileged = true
    s.inline = "sed -i '/tty/!s/mesg n/tty -s \\&\\& mesg n/' /root/.profile"
  end
```

**Comment by richard-scott** [comment] 2017-01-24 10:44
I add this to my Vagrantfile to fix this:

```
  config.vm.provision "fix-no-tty", type: "shell" do |s|
    s.privileged = true
    s.inline = "sed -ri s'/(mesg n)/tty -s \1 || true /' /root/.profile"
  end
```

**Comment by agabert** [comment] 2017-04-25 09:31
this happens to me when i call scripts with #!/usr/bin/env bash instead of #!/bin/bash

s.vm.provision :shell, path: "scripts/sbin/bootstrap.sh"

if the shebang in this bootstrap.sh file is #!/usr/bin/env bash then i can reproduce the above error with Inappropriate ioctl for device on my MBP

**Comment by jchook** [comment] 2017-05-10 03:20
I had the "mesg: ttyname failed: Inappropriate ioctl for device" issue with Vagrant 1.9.1 but it was fixed by upgrading to 1.9.4, in case anyone is googling this.

**Comment by Gundars** [comment] 2017-09-21 09:33
Nope, 1.9.7, still happening

**Comment by lastsky** [comment] 2018-05-26 22:03
```DIFF
 Vagrant.configure("2") do |config|
+  config.ssh.shell="bash"
   config.vm.box = "ubuntu/xenial64"
   config.vm.provider "virtualbox" do |v|
     v.customize [ "modifyvm", :id, "--memory", 2048 ]
     v.customize [ "modifyvm", :id, "--cpus", 2 ]
   end
```

solves this for me on mac os x.
