### ISSUE TITLE
CentOS Stream 9 not found on Vagrant Cloud

### ISSUE THREAD

**Issue by vancanhuit** [chef/bento#1432] opened 2022-11-01 14:41 UTC
# Problem

I can't find the CentOS Stream 9 box on Vagrant Cloud: [https://app.vagrantup.com/bento](https://app.vagrantup.com/bento).

# Expected Result:

CentOS Stream 9 box is available on Vagrant Cloud.

**Comment by elreydetoda** [comment] 2022-11-04 02:08
Duplicate of #1391

**Comment by Stromweld** [comment] 2023-01-20 17:50
box released at https://app.vagrantup.com/bento/boxes/centos-stream-9/versions/202301.20.0

**Closed by Stromweld** 2023-01-20 17:50 UTC
Labels: Status: Untriaged
