### ISSUE TITLE
centos-7 ssh connection times out with more interfaces added

### ISSUE THREAD

**Issue by nusenu** [chef/bento#1032] opened 2018-05-05 15:56 UTC
The centos-7 box fails to come up / be reachable via SSH when more network interfaces are added.

reproducer:
```
git clone https://github.com/nusenu/ansible-relayor.git
cd ansible-relayor
kitchen create t-exit-6publicIPs-dedicatedExitIP-2instPerIP-centos-7
```
--> fails to create

the relevant part from .kitchen.yml:
```
  - name: t-exit-6publicIPs-dedicatedExitIP-2instPerIP
    driver:
      network:
      - ["private_network", {ip: "192.0.2.10"}]
      - ["private_network", {ip: "198.51.100.10"}]
      - ["private_network", {ip: "198.51.100.11"}]
      - ["private_network", {ip: "198.51.100.12"}]
      - ["private_network", {ip: "198.51.100.13"}]
      - ["private_network", {ip: "198.51.100.14"}]
```

**Comment by cheeseplus** [comment] 2018-05-07 17:28
The question here is does Vagrant even support this properly as we're just passing config along - this could be a Vagrant issue or one with the box but we need a bunch more detail.

**Comment by nusenu** [comment] 2018-05-26 16:39
I had some time to look into this some more:
- debian-9 box works fine with that many interface, so Vagrant supports it and this appears to be a box specific problem.

- this works:
```
Vagrant.configure("2") do |c|
  c.vm.box = "bento/centos-7"
  c.vm.network(:private_network, {:ip=>"192.0.2.10"})
  c.vm.network(:private_network, {:ip=>"198.51.100.10"})
end
```

if you add one more interface it fails:

```
Vagrant.configure("2") do |c|
  c.vm.box = "bento/centos-7"
  c.vm.network(:private_network, {:ip=>"192.0.2.10"})
  c.vm.network(:private_network, {:ip=>"198.51.100.10"})
  c.vm.network(:private_network, {:ip=>"198.51.100.11"})
end
```

Inspecting the created virtualbox via the console, shows that the VM has 4 interfaces 
but /etc/sysconfig/network-scripts/ contains only a single ifcfg-* file (ifcfg-enp0s10) not containing any static IP addresses.

This has been tested with v201803.24.0

Can you confirm this with the above Vagrantfile?

**Comment by nqb** [comment] 2018-09-15 13:54
Hello @nusenu,

I was able to reproduce the issue but since the upgrade of following components:
- Vagrant 2.1.5
- latest bento/centos-7.5 (201808.24.0)
- Virtualbox Extensions Pack 5.2.18

the issues has been solved.

Hope that helps.

**Comment by nusenu** [comment] 2018-09-15 13:58
thanks a lot!

**Comment by cheeseplus** [comment] 2018-09-15 14:03
I think we may have inadvertently solved this with the reversion of Consistent Interface Naming (now you get eth0 instead of ens3p02) - closing.

**Closed by cheeseplus** 2018-09-15 14:03 UTC

**Comment by nqb** [comment] 2018-09-15 14:13
@cheeseplus : you are 100% right.
