### ISSUE TITLE
opscode-centos-7.1 Virtualbox box not able to NFS mount

### ISSUE THREAD

**Issue by andytson** [chef/bento#388] opened 2015-07-02 20:41 UTC
It seems a change has been done in a build of opscode-centos-7.1 that is causing for some reason, the private network static ip to not be assigned before vagrant mounts nfs. This causes nfs to fail.

Checking the ip address assignment after the failure shows the static ip isn't assigned. An ifdown and ifup of the private network adapter introduces the static IP.

This wasn't an issue in an earlier opscode-centos-7.1 build (if you did one before that, or it was just me manually building the working one before you released it), nor opscode-centos-7.0.

Using vboxsf, the static ip is assigned to the private network adapter after boot.

Steps to recreate

* import opscode-centos-7.1
* vagrant init opscode-centos-7.1
* edit Vagrantfile to add a private network with a static ip of 33.33.33.15, and add a synced folder with NFS
* vagrant up

causes:
```
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Configuring and enabling network interfaces...
==> default: Exporting NFS shared folders...
==> default: Preparing to edit /etc/exports. Administrator privileges will be required...
Password:
==> default: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' 33.33.33.1:'/Users/andy' /vagrant

Stdout from the command:



Stderr from the command:

mount.nfs: access denied by server while mounting 33.33.33.1:/Users/andy
```

**Comment by davemac30** [comment] 2015-07-13 12:14
I believe this is similar to a problem I am having with private_network using chef/centos-7.1.

When my machine first boots, it get it's private network interface (enp0s8, in my case) configured as expected:

```
va ssh -c "ip a s enp0s8"
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:26:7d:7e brd ff:ff:ff:ff:ff:ff
    inet 192.168.33.10/24 brd 192.168.33.255 scope global enp0s8
       valid_lft forever preferred_lft forever
    inet6 fe80::a00:27ff:fe26:7d7e/64 scope link 
       valid_lft forever preferred_lft forever
```

A few seconds later, however, the i/f's ipv4 config is gone:

```
$ va ssh -c "ip a s enp0s8"
3: enp0s8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 08:00:27:26:7d:7e brd ff:ff:ff:ff:ff:ff
    inet6 fe80::a00:27ff:fe26:7d7e/64 scope link 
       valid_lft forever preferred_lft forever
```

I believe this is something to do with the way vagrant configures the private_network dynamically, when it first brings the box up, not being compatible with NetworkManager. Even though the static config created by vagrant (/etc/sysconfig/network-scripts/ifcfg-enp0s8) contains the line "NM_CONTROLLED=no", NetworkManager seems to be aware of the interface:

```
# nmcli c
NAME                UUID                                  TYPE            DEVICE 
Wired connection 1  edbeb169-7e0e-4596-af02-b81bd9b502c4  802-3-ethernet  enp0s8 
enp0s3              3c36b8c2-334b-57c7-91b6-4401f3489c69  802-3-ethernet  enp0s3
```

journalctl shows that NetworkManager trying to do DHCP on the interface, which of course fails. Eventually NetworkManager marks the interface disconnected.

restarting NetworkManager and the network makes everything ok, presumably because configs are loaded from /etc/sysconfig/network-scripts. Likewise a reboot clears it.

I don't think this is a problem with the box, rather it's a shortcoming of vagrant's approach to dynamic configuration of a network i/f when NetworkManager is active.

**Comment by cheeseplus** [comment] 2015-10-07 19:33
Does this condition still exist with the latest (2.2.2) release? Also is this a bento specific issue or a general vagrant issue?

**Comment by rickard-von-essen** [comment] 2015-10-08 06:19
Can't reproduce this with bento/centos-7.1 (v2.2.2) and Vagrant 1.7.4.

**Comment by cheeseplus** [comment] 2015-10-08 06:56
In that case closing for now, feel free to re-open should the condition arise again.

**Comment by legal90** [comment] 2016-06-18 19:30
@cheeseplus @rickard-von-essen It seems like we have a similar issue with `parallels` provider, with a 100% reproduction scenario: https://github.com/Parallels/vagrant-parallels/issues/265

It was fixed in Boxcutter by https://github.com/boxcutter/centos/commit/be4174ea6e8c053d25f970d524d1801c6b21c55f

**Closed** 2016-07-09 16:17 UTC
Labels: Developing
