### ISSUE TITLE
CentOS and Fedora boxes packed without docs?

### ISSUE THREAD

**Issue by shortdudey123** [chef/bento#317] opened 2015-02-04 17:02 UTC
[Some cookbooks](https://github.com/hw-cookbooks/auditd/pull/15#issuecomment-72838561) rely on copying default or example configs out of the package docs.  Testing this does not appear possible under the CentOS 6.5 and newer boxes since they are [excluded](https://github.com/chef/bento/blob/1da76931d0aacbf20bf21033ee10f7e4a7e7d882/packer/http/centos-6.6/ks.cfg#L22).  Same with [Fedora](https://github.com/chef/bento/blob/1da76931d0aacbf20bf21033ee10f7e4a7e7d882/packer/http/fedora-19/ks.cfg#L27).

Any reason to not include them in the future?

Kudos to @chewi for tracking it down

**Comment by juliandunn** [comment] 2015-02-04 20:29
It's to keep the box sizes small. And also, I'd argue it's not best practice for the cookbook author to be doing things like `IO.read` of files and copying them places. That's not guaranteed to be reproducible every time.

**Comment by shortdudey123** [comment] 2015-02-04 20:56
What would be a better way to get the example configs then?  I guess they could be pulled from the project source online

Specific example:
https://github.com/hw-cookbooks/auditd/blob/master/providers/builtins.rb#L28
https://github.com/hw-cookbooks/auditd/blob/master/providers/builtins.rb#L33

**Comment by chewi** [comment] 2015-02-04 21:12
To be honest, I'm not a big fan of the "built-in rules" feature either. I only fixed it up because it was already there and needed improving. Do people really use these rules as-is? We'll be writing our own. Evidently someone saw fit to implement this but they could have just as easily written a wrapper cookbook for their own needs.

I once did something similar to instantiate the rsyslog database using a schema from /usr/share/doc but that was never merged and I suppose I could have simply included the schema in the cookbook.

**Comment by shortdudey123** [comment] 2015-02-04 21:58
Agree, i am not a fan either

**Comment by juliandunn** [comment] 2015-02-07 21:21
@shortdudey123 yeah, the best idea is to pull the configs from a known source (bundling them inside the cookbook is one option). As such I'm going to close this issue as "won't fix".

**Closed by juliandunn** 2015-02-07 21:21 UTC
