### ISSUE TITLE
Ubuntu-16.04 networking failed

### ISSUE THREAD

**Issue by rbas** [chef/bento#586] opened 2016-05-05 11:40 UTC
Hi,
configuration network interfaces failed.
```
==> default: Configuring and enabling network interfaces...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifdown eth1 2> /dev/null

Stdout from the command:


Stderr from the command:

mesg: ttyname failed: Inappropriate ioctl for device
```
```
vagrant box update --box bento/ubuntu-16.04
Checking for updates to 'bento/ubuntu-16.04'
Latest installed version: 2.2.6
Version constraints: > 2.2.6
Provider: virtualbox
```

I checked interfaces in VM and eth1 is renamed to enp0s3
```
cat /etc/network/interfaces
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto enp0s3
iface enp0s3 inet dhcp
pre-up sleep 2
```

**Comment by legal90** [comment] 2016-05-05 11:56
Looks like duplicate of  #585 
Also related: https://github.com/chef/bento/pull/545#issuecomment-213074773

This is the issue of Vagrant and it was fixed in https://github.com/mitchellh/vagrant/pull/7159. Looking forward the next version of Vagrant (> 1.8.1) to be released.

**Closed by legal90** 2016-05-05 11:56 UTC

**Comment by amirkoklan** [comment] 2016-05-05 12:46
when can we have the new version of Vagrant which has solved this issue ? 
there is not a temporary workaround without a new update ?

**Comment by cheeseplus** [comment] 2016-05-05 15:22
You can manually apply the patch from the posted fix (that is what I did) which is super hacky but works. Or you can run vagrant from source. Either way, there isn't much we, the bento team, can do to get a release of Vagrant cut.
