### ISSUE TITLE
Guest Additions are installed without dkms support

### ISSUE THREAD

**Issue by rahulverma** [chef/bento#332] opened 2015-03-11 10:58 UTC
If the guest linux kernel version gets updated then Vagrant fails to mount host directories. This is because the kernel module vboxsf was compiled for an older version of the kernel.
This gets fixed after installing dkms and then reinstalling guest additions.
`yum install dkms`

It would be much more convenient if guest additions were compiled from the start with dkms support.

##### Example error:
```
Failed to mount folders in Linux guest. This is usually because
the "vboxsf" file system is not available. Please verify that                                                                                                                                        
the guest additions are properly installed in the guest and                                                                                                                                          
can work properly. The command attempted was:                                                                                                                                                        

mount -t vboxsf -o uid=`id -u vagrant`,gid=`getent group vagrant | cut -d: -f3`,dmode=777,fmode=666 db_data /db_data                                                                                 
mount -t vboxsf -o uid=`id -u vagrant`,gid=`id -g vagrant`,dmode=777,fmode=666 db_data /db_data                                                                                                      

The error output from the last command was:                                                                                                                                                          

/sbin/mount.vboxsf: mounting failed with the error: No such device
```

**Comment by juliandunn** [comment] 2015-03-11 22:08
So the reason the boxes are set up this way is to keep their size down. Otherwise you need a whole C compiler, make, etc. on the box which is undesirable.

Generally, the use cases for the Bento boxes are for userland testing, which are generally agnostic to the kernel version.

**Comment by matthew-campbell** [comment] 2015-03-19 16:22
You could alternatively use [veewee](https://github.com/jedi4ever/veewee) for they compile Guest Additions with dkms.

**Comment by juliandunn** [comment] 2015-03-19 16:26
Or just maintain a fork if you don't like how we set up these boxes :grin: 

I'm closing this because it's "by design".

**Closed by juliandunn** 2015-03-19 16:26 UTC

**Comment by rahulverma** [comment] 2015-03-19 17:35
Thanks. I will go ahead and try veewee.
