### ISSUE TITLE
No networking for CentOS 7.2 on Mac host

### ISSUE THREAD

**Issue by dgivens** [chef/bento#701] opened 2016-10-20 21:47 UTC
I've been unable to get networking to work with bento/centos-7.2. Host is a Mac and I'm running VirtualBox 5.0.28 r111378. Basically, the network interface in the VM shows the link down, so it's unable to obtain an IP address via DHCP. I've changed the interface type from NAT to NAT Network, Host-Only Adaptor, and switched the Adapter Type to various others from the Intel Pro 1000 to virtio, all with the same result.

To check my sanity, I've spun up another CentOS 7.2 VM from the CentOS install image with the default Intel Pro 1000 MT Desktop adapter type and NAT adapter, and it has worked as expected. 

I'm scratching my head. I don't know what the difference is, but the bento image just isn't working for me.

**Comment by cheeseplus** [comment] 2016-10-20 22:26
@dgivens what version of the centos-7.2 box and Vagrant are you using?

If it's box 2.3.0, these were built with Virtualbox  5.1.6 and won't work with earlier versions. Pinning to 2.2.9 or upgrading are the best options.

**Comment by dgivens** [comment] 2016-10-25 16:19
I upgraded to Virtualbox 5.1.8 and with the 2.3.0 box, still no networking. I'll try 2.2.9.

**Comment by cheeseplus** [comment] 2016-10-25 21:17
2.2.9 won't work (at least it shouldn't in our experience)

2.2.9 was built with 5.0.26 tools (due to issues in the 5.1 branch) and 5.1 is a breaking upgrade. You might want to remove any imported boxes as anything imported with old versions will break (the vbox bug is on the import function itself) just to be sure.

**Comment by cheeseplus** [comment] 2016-10-25 22:59
Looks like from talking to @tas50 we're seeing some major regressions in 5.1.8 so I'd recommend sticking with 5.1.6.

**Comment by cheeseplus** [comment] 2016-10-27 20:02
@dgivens any luck downgrading to 5.1.6 as per above comment?

**Comment by dgivens** [comment] 2016-10-28 19:36
Sorry for the delay. @cheeseplus I'm downloading 5.1.6 now and will let you know shortly.

**Comment by dgivens** [comment] 2016-10-28 19:56
@cheeseplus Yes, vbox 5.1.6 and centos-7.2 2.3.0 works as expected. Way to go VirtualBox.

**Comment by cheeseplus** [comment] 2016-10-28 20:37
@dgivens great to know and I'll close this one out but here is hoping we get relief soon

**Closed** 2016-10-28 20:44 UTC
