### ISSUE TITLE
centos8 box can't compile VBox Guest Additions

### ISSUE THREAD

**Issue by athnariel** [chef/bento#1345] opened 2021-03-20 14:51 UTC
# Describe the problem
When starting a box that needs Guest Additions, the provisioning fails with the following:
```
==> default: Checking for guest additions in VM...
    default: No guest additions were detected on the base box for this VM! Guest
    default: additions are required for forwarded ports, shared folders, host only
    default: networking, and more. If SSH fails on this machine, please install
    default: the guest additions and repackage the box to continue.
    default:
    default: This is not an error message; everything may continue to work properly,
    default: in which case you may ignore this message.
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /Users/mpapini/Oracle/vagrant-tests/centos8_odi
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 vagrant /vagrant

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device
```
The box should include the packages: **kernel-devel gcc make perl elfutils-libelf-devel**

## Software Version
bento/centos-8 and bento/centos-8.3

## Possible Solution

Include the packages **kernel-devel gcc make perl elfutils-libelf-devel** in the box

**Comment by mdepot** [comment] 2021-05-26 13:34
I see this problem as well.  If the kernel is updated after the build, the newer kernel headers and a compiler are needed by vagrant-vbguest to rebuild the vbox guest additions during deployment.  This seems to actually be a regression, as the kernel-headers, kernel-devel, and gcc packages were removed from the kickstart files in a commit on 10/22/2020, and then the make and perl packages were removed on 10/23/2020.  Note this applies to both CentOS 7 and 8.  It may apply to other RHEL/Fedora flavors as well, but I didn't dig any deeper into the commit history.

**Comment by mdepot** [comment] 2021-05-26 16:10
Looking at this closer, perhaps the best place to fix this is in virtualbox.sh.  This script removes some of those packages at the end of the build, however they need to remain in case vagrant-vbguest tries to rebuild the vbox additions at the time of 'vagrant up'

**Comment by mukunda-** [comment] 2022-07-24 16:12
I also see a note in the post kernel update script from the virtualbox scripts, so the fault doesn't entirely seem to be on bento:

```
    cat << EOF > /etc/kernel/postinst.d/vboxadd
#!/bin/sh
# This only works correctly on Debian derivatives - Red Hat calls it before
# installing the right header files.
/sbin/rcvboxadd quicksetup "\${1}"
exit 0
EOF
```

**Comment by Stromweld** [comment] 2023-01-20 16:30
Closing this issue due to age. Please feel free to re-open or submit a new issue if the problem still exists with the latest version of the bento code.

**Closed by Stromweld** 2023-01-20 16:30 UTC
